### ISSUE TITLE
Race condition when using Grizzly provider causes SingleEndpointPool to block completely.

### ISSUE THREAD

**Issue by dfeist** [AsyncHttpClient/async-http-client#1062]
Because GrizzlyAsyncHttpProvider uses IdleTimeoutFilter for handling responseTimeout and this uses a  different DelayedExecutor instance to that used by SingleEndpointPool.KeepAliveCleaner a race condition can occur when two different threads attempt to close/cleanup connections at the same time.  The result is that one thread (KeepAliveCleaner) gets stuck in an infinite loop while all other threads are blocked; both those attempting to do a take() as well as the thread used for the IdleTimoutFilter that is blocked on 'poolSync' because the other thread is still has this lock.

Disabling keepAlive by setting a negative timeout avoids this issue of course.

//cc @oleksiys 

The two threads of interest are:

**"connection-pool-delays-thread-pool(1)"** daemon prio=10 tid=0x00007ffaf14bc800 nid=0xb3 runnable [0x00007ffaee356000]
   java.lang.Thread.State: RUNNABLE
	at org.glassfish.grizzly.nio.NIOConnection.closeSilently(NIOConnection.java:495)
	at org.glassfish.grizzly.connectionpool.SingleEndpointPool.cleanupIdleConnections(SingleEndpointPool.java:1106)
	- locked <0x00000000e3c84800> (a java.lang.Object)
	at org.glassfish.grizzly.connectionpool.SingleEndpointPool$KeepAliveCleaner.doWork(SingleEndpointPool.java:1395)

**"Grizzly-IdleTimeoutFilter-IdleCheck"** daemon prio=10 tid=0x00007ffaf14bb800 nid=0xb2 waiting for monitor entry [0x00007ffaee457000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at org.glassfish.grizzly.connectionpool.SingleEndpointPool$PoolConnectionCloseListener.onClosed(SingleEndpointPool.java:1330)
	- waiting to lock <0x00000000e3c84800> (a java.lang.Object)
	at org.glassfish.grizzly.connectionpool.SingleEndpointPool$PoolConnectionCloseListener.onClosed(SingleEndpointPool.java:1323)
	at org.glassfish.grizzly.nio.NIOConnection.invokeCloseListener(NIOConnection.java:955)
	at org.glassfish.grizzly.nio.NIOConnection.notifyCloseListeners(NIOConnection.java:828)
	at org.glassfish.grizzly.nio.NIOConnection.terminate0(NIOConnection.java:561)
	at org.glassfish.grizzly.nio.transport.TCPNIOConnection.terminate0(TCPNIOConnection.java:291)
	at org.glassfish.grizzly.nio.NIOConnection$3.completed(NIOConnection.java:524)
	at org.glassfish.grizzly.nio.NIOConnection$3.completed(NIOConnection.java:520)
	at org.glassfish.grizzly.asyncqueue.AsyncWriteQueueRecord.notifyCompleteAndRecycle(AsyncWriteQueueRecord.java:173)
	at org.glassfish.grizzly.nio.AbstractNIOAsyncQueueWriter.write(AbstractNIOAsyncQueueWriter.java:279)
	at org.glassfish.grizzly.nio.AbstractNIOAsyncQueueWriter.write(AbstractNIOAsyncQueueWriter.java:169)
	at org.glassfish.grizzly.nio.AbstractNIOAsyncQueueWriter.write(AbstractNIOAsyncQueueWriter.java:71)
	at org.glassfish.grizzly.AbstractWriter.write(AbstractWriter.java:76)
	at org.glassfish.grizzly.nio.NIOConnection.closeGracefully0(NIOConnection.java:519)
	at org.glassfish.grizzly.nio.NIOConnection.closeWithReason(NIOConnection.java:500)
	at com.ning.http.client.providers.grizzly.GrizzlyAsyncHttpProvider.timeout(GrizzlyAsyncHttpProvider.java:431)

**Comment by oleksiys** [comment]
Thank you!
Fixing it...

**Comment by dfeist** [comment]
I have a fix locally, basically what i do is pass the DelayedExecutor created in GrizzlyAsyncHttpProvider to grizzly via connection pool constructor.  Pretty simple fix, but I can create a PR if you like (i don't have a test yet though)

**Comment by oleksiys** [comment]
Grizzly issue:
https://java.net/jira/browse/GRIZZLY-1820

IMO it's connection-pool issue, but we can apply both fixes.
Once new grizzly snapshot is available, I'd like to ask you to double check the fix.
Would it be possible?

**Comment by dfeist** [comment]
Depends if the idea is that connection-pool should support multiple threads doing keepAlive/timeout operations concurrently or not, if it should support this, then sure a fix grizzly-side would be preferred.

Can try to validate a fix, but to be honest haven't really been able to reproduce these easily myself yet..

**Comment by oleksiys** [comment]
Could you pls. try if the issue is still reproducible with the Grizzly 2.3.24-SNAPSHOT?

**Comment by dfeist** [comment]
Sure, will test this Monday.  Do you have a link to commit, I couldn't find it.

**Comment by oleksiys** [comment]
https://java.net/projects/grizzly/sources/git/revision/96010f9992cf9639e9bed4602d75f181720333aa

**Comment by dfeist** [comment]
I commented in the grizzly issue already, but just to confirm that this commit resolves this issue.

**Comment by oleksiys** [comment]
Thank you for confirming!
