### ISSUE TITLE
when too many request ,error

### ISSUE THREAD

**Issue by benkris1** [AsyncHttpClient/async-http-client#1074]
when the service is start,it is run well,but after some request,it throw the error.
```java
 AsyncHttpProviderConfig<String, Object> asyncHttpProviderConfig = new NettyAsyncHttpProviderConfig();

    // Configure the AsyncHttpClientConfig via its builder. Can set things like idle connection timeout, request
    // timeout, etc.
    AsyncHttpClientConfig.Builder asyncHttpClientConfigBuilder = new AsyncHttpClientConfig.Builder();
    asyncHttpClientConfigBuilder.setAsyncHttpClientProviderConfig(asyncHttpProviderConfig);
    asyncHttpClientConfigBuilder.setRequestTimeoutInMs(2000);
    asyncHttpClientConfigBuilder.setMaximumConnectionsTotal(1000);

    AsyncHttpClientConfig asyncHttpClientConfig = asyncHttpClientConfigBuilder.build();

    // Use Netty as the concrete implementation of the transport layer.
    NettyAsyncHttpProvider nettyAsyncHttpProvider = new NettyAsyncHttpProvider(asyncHttpClientConfig);

    asyncHttpClient = new AsyncHttpClient(nettyAsyncHttpProvider, asyncHttpClientConfig);




 boundRequestBuilder.execute(new AsyncCompletionHandler<Response>() {
          @Override
          public void onThrowable(Throwable t) {
            logger.error(t.getMessage(),t);
            subscriber.onError(new LeapProxyException(LASException.INTERNAL_SERVER_ERROR, t.getMessage()));
          }

          @Override
          public Response onCompleted(Response response) throws Exception {
            int statusCode = response.getStatusCode();
            if(statusCode == 200 || statusCode == 201) {
              logger.debug("{},success, response {}",url,response.getResponseBody());
              subscriber.onNext(data(response.getResponseBody("UTF-8"),clazz));

            }else {
              subscriber.onError(new LeapProxyException(statusCode,response.getResponseBody()));
            }
            return response ;
          }
        });

      } catch (IOException e) {
        logger.error(e.getMessage(),e);
        subscriber.onError(e);
      }
    });
```

```
as.leap.ama.base.exception.LeapProxyException: http://apiuat.leap.as/2.0/help/cu_service
	at as.leap.ama.base.proxy.impl.LeapHttpProxy$1.onThrowable(LeapHttpProxy.java:97)
	at com.ning.http.client.providers.netty.NettyResponseFuture.abort(NettyResponseFuture.java:330)
	at com.ning.http.client.providers.netty.NettyConnectListener.operationComplete(NettyConnectListener.java:107)
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:427)
	at org.jboss.netty.channel.DefaultChannelFuture.addListener(DefaultChannelFuture.java:145)
	at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.doConnect(NettyAsyncHttpProvider.java:1108)
	at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.execute(NettyAsyncHttpProvider.java:932)
	at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.nextRequest(NettyAsyncHttpProvider.java:1385)
	at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.nextRequest(NettyAsyncHttpProvider.java:1381)
	at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.remotelyClosed(NettyAsyncHttpProvider.java:1496)
	at com.ning.http.client.providers.netty.NettyConnectListener.operationComplete(NettyConnectListener.java:95)
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:427)
	at org.jboss.netty.channel.DefaultChannelFuture.addListener(DefaultChannelFuture.java:145)
	at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.doConnect(NettyAsyncHttpProvider.java:1108)
	at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.execute(NettyAsyncHttpProvider.java:928)
	at com.ning.http.client.AsyncHttpClient.executeRequest(AsyncHttpClient.java:513)
	at com.ning.http.client.AsyncHttpClient$BoundRequestBuilder.execute(AsyncHttpClient.java:231)
	at as.leap.ama.base.proxy.impl.LeapHttpProxy.lambda$proxy$4(LeapHttpProxy.java:93)
	at as.leap.ama.base.proxy.impl.LeapHttpProxy$$Lambda$41/1009418524.call(Unknown Source)
	at rx.Observable.unsafeSubscribe(Observable.java:8587)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.handleNewSource(OperatorMerge.java:190)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:160)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:96)
	at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:54)
	at rx.subjects.SubjectSubscriptionManager$SubjectObserver.onNext(SubjectSubscriptionManager.java:224)
	at rx.subjects.AsyncSubject.onCompleted(AsyncSubject.java:96)
	at rx.util.async.Async$1$1.call(Async.java:533)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:43)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by slandelle** [comment]
What's the original exception?

**Comment by benkris1** [comment]
```java
	at org.apache.curator.ConnectionState.checkTimeouts(ConnectionState.java:197)
	at org.apache.curator.ConnectionState.getZooKeeper(ConnectionState.java:87)
	at org.apache.curator.CuratorZookeeperClient.getZooKeeper(CuratorZookeeperClient.java:115)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.getZooKeeper(CuratorFrameworkImpl.java:477)

�
        at com.ning.http.client.AsyncHttpClient$BoundRequestBuilder.execute(AsyncHttpClient.java:231)
        at as.leap.ama.base.proxy.impl.LeapHttpProxy.lambda$proxy$4(LeapHttpProxy.java:93)
        at as.leap.ama.base.proxy.impl.LeapHttpProxy$$Lambda$41/1009418524.call(Unknown Source)
        at rx.Observable.unsafeSubscribe(Observable.java:8587)rx.internal.operators.OperatorMerge$MergeSubscriber.handleNewSource(OperatorMerge.java:190)
        at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:160)
        at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:96)
        at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:54)
        at rx.subjects.SubjectSubscriptionManager$SubjectObserver.onNext(SubjectSubscriptionManager.java:224)
        at rx.subjects.AsyncSubject.onCompleted(AsyncSubject.java:96)
        at rx.util.async.Async$1$1.call(Async.java:533)
        at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:43)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.nio.channels.ClosedByInterruptException
        at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:202)
        at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:659)
        at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink.connect(NioClientSocketPipelineSink.java:108)
        at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink.eventSunk(NioClientSocketPipelineSink.java:70)
        at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.handleDownstream(OneToOneEncoder.java:54)
        at org.jboss.netty.handler.codec.http.HttpClientCodec.handleDownstream(HttpClientCodec.java:97)
        at org.jboss.netty.handler.stream.ChunkedWriteHandler.handleDownstream(ChunkedWriteHandler.java:109)
        at org.jboss.netty.channel.Channels.connect(Channels.java:634)
        at org.jboss.netty.channel.AbstractChannel.connect(AbstractChannel.java:207)
        at org.jboss.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:229)
        at org.jboss.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:182)
        at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.doConnect(NettyAsyncHttpProvider.java:1066)
```

**Comment by benkris1** [comment]
Thank you !

**Comment by slandelle** [comment]
That's a user issue: you're somehow interrupting threads when they are trying to connect sockets (java.nio.channels.ClosedByInterruptException).
