### ISSUE TITLE
Multipart File requests fail with IllegalArgumentException  (on +1.9.2)

### ISSUE THREAD

**Issue by maesenka** [AsyncHttpClient/async-http-client#1126]
All multipart file requests in versions 1.9.36 result in IllegalArgumentExceptions. 

```
016-04-02 14:04:24,459 [New I/O worker #35] WARN  - AbstractNioSelector: Unexpected exception in the selector loop.
java.lang.IllegalArgumentException: writtenAmount must be a positive integer: -1
	at org.jboss.netty.channel.DefaultWriteCompletionEvent.<init>(DefaultWriteCompletionEvent.java:36) ~[netty-3.10.5.Final.jar:na]
	at org.jboss.netty.channel.Channels.fireWriteComplete(Channels.java:324) ~[netty-3.10.5.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.write0(AbstractNioWorker.java:299) [netty-3.10.5.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.writeFromSelectorLoop(AbstractNioWorker.java:158) [netty-3.10.5.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:114) [netty-3.10.5.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337) ~[netty-3.10.5.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) [netty-3.10.5.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) [netty-3.10.5.Final.jar:na]
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [netty-3.10.5.Final.jar:na]
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [netty-3.10.5.Final.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_40]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_40]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_40]
```

I'm pretty sure that the bug was introduced in commit 54def5ad043ea8af8beb2aa820f2c0efa9fc1980. If I revert this commit my MultiPart file requests succeed.

**Comment by slandelle** [comment]
Could you provide a reproducer, please?

**Comment by slandelle** [comment]
Fixed. Thanks for reporting
