### ISSUE TITLE
Failure updating channel promise

### ISSUE THREAD

**Issue by marenzo** [AsyncHttpClient/async-http-client#1218]
I'm currently upgrading our usage of AHC to version 2 (`2.0.10` be specifically), and sometimes, randomly one of my tests fails with the following exception:

```
[nioEventLoopGroup-2-9] 12:12:09,941  WARN ChannelOutboundBuffer:146 - Failed to mark a promise as success because it has failed already: DefaultChannelPromise@70dda153(failure: io.netty.handler.codec.EncoderException: io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1), unnotified cause io.netty.handler.codec.EncoderException: io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:106)
	at io.netty.channel.CombinedChannelDuplexHandler.write(CombinedChannelDuplexHandler.java:345)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:742)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:734)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:819)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:727)
	at io.netty.handler.stream.ChunkedWriteHandler.doFlush(ChunkedWriteHandler.java:306)
	at io.netty.handler.stream.ChunkedWriteHandler.flush(ChunkedWriteHandler.java:139)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:780)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:806)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:817)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:798)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1012)
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:261)
	at org.asynchttpclient.netty.request.NettyRequestSender.writeRequest(NettyRequestSender.java:354)
	at org.asynchttpclient.netty.channel.NettyConnectListener.writeRequest(NettyConnectListener.java:93)
	at org.asynchttpclient.netty.channel.NettyConnectListener.onSuccess(NettyConnectListener.java:136)
	at org.asynchttpclient.netty.request.NettyChannelConnector$1.onSuccess(NettyChannelConnector.java:92)
	at org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:26)
	at org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:20)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:514)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:507)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:486)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:427)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:111)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:82)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:251)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:286)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:589)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:513)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:427)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:399)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
Caused by: io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:101)
	at io.netty.handler.codec.http.DefaultFullHttpRequest.release(DefaultFullHttpRequest.java:77)
	at io.netty.util.ReferenceCountUtil.release(ReferenceCountUtil.java:59)
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90)
	... 34 more
```

All the test does is setting up new local server, sending request and validating the response, nothing special, nothing concurrent.

Some note that for some reason it mostly happens on same method test, but with the previous client never had anything similar to that.

Also to note, I'm constructing AHC with a static event loop group to not create new stack each time a client being constructed, and sharing same timer for all instances, but I don't think it can cause such thing.

And last thing, upgrading to `2.0.11` (which also using latest Netty version) seems to be fine for now - but as said, happens randomly, and I'm not sure it solved the issue.

If I'm missing on any information please update, and I'm also reading the code now to see what can cause it.

**Comment by marenzo** [comment]
Update: happened now also with `2.0.11`, same stacktrace:
```
[nioEventLoopGroup-2-9] 15:58:20,672  WARN ChannelOutboundBuffer:146 - Failed to mark a promise as success because it has failed already: DefaultChannelPromise@6eb847ef(failure: io.netty.handler.codec.EncoderException: io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1), unnotified cause io.netty.handler.codec.EncoderException: io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:106)
	at io.netty.channel.CombinedChannelDuplexHandler.write(CombinedChannelDuplexHandler.java:345)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:742)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:734)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:819)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:727)
	at io.netty.handler.stream.ChunkedWriteHandler.doFlush(ChunkedWriteHandler.java:306)
	at io.netty.handler.stream.ChunkedWriteHandler.flush(ChunkedWriteHandler.java:139)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:780)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:806)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:817)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:798)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1012)
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:261)
	at org.asynchttpclient.netty.request.NettyRequestSender.writeRequest(NettyRequestSender.java:355)
	at org.asynchttpclient.netty.channel.NettyConnectListener.writeRequest(NettyConnectListener.java:93)
	at org.asynchttpclient.netty.channel.NettyConnectListener.onSuccess(NettyConnectListener.java:136)
	at org.asynchttpclient.netty.request.NettyChannelConnector$1.onSuccess(NettyChannelConnector.java:92)
	at org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:26)
	at org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:20)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:514)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:507)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:486)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:427)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:111)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:82)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:251)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:286)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:589)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:513)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:427)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:399)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
Caused by: io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:101)
	at io.netty.handler.codec.http.DefaultFullHttpRequest.release(DefaultFullHttpRequest.java:77)
	at io.netty.util.ReferenceCountUtil.release(ReferenceCountUtil.java:59)
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90)
	... 34 more
```

**Comment by slandelle** [comment]
What does your request look like?
What does your AHC config look like?
Do you force the Netty version to be older that the one AHC depends on (latest 4.0.39)?

**Comment by marenzo** [comment]
Request:
Not sure what you exactly mean, but sending POST request to localhost, with some byte-array body (MsgPack serialization payload), setting content-type, nothing more than that.
Also, executing the request with `AsyncHandler` implementation. The response from the server is chunked, so reading part by part.

--
Configuration (Referencing to the build part):
https://github.com/outbrain/ob1k/blob/ahc_upgrade/ob1k-http/src/main/java/com/outbrain/ob1k/http/HttpClient.java#L348
```java
final DefaultAsyncHttpClientConfig.Builder configBuilder = new DefaultAsyncHttpClientConfig.Builder().
        setConnectTimeout(connectionTimeout). // 10000 in the test
        setMaxRequestRetry(retries). // 3
        setRequestTimeout(requestTimeout).  // -1 in the test
        setCompressionEnforced(compressionEnforced). // false
        setDisableUrlEncodingForBoundRequests(disableUrlEncoding). // false
        setMaxConnectionsPerHost(maxConnectionsPerHost). // 100
        setMaxConnections(maxTotalConnections). // 200
        setChunkedFileChunkSize(chunkedFileChunkSize). // 65k
        setNettyTimer(NettyTimerHolder.TIMER). // shared timer
        setEventLoopGroup(EventLoopGroupHolder.GROUP). // shared ELG
        setFollowRedirect(followRedirect).// true
```

--
Nope, using also latest version.

**Comment by slandelle** [comment]
Could you please check what happens if you disable retry (config setMax(Retry(0))?

**Comment by marenzo** [comment]
Now having new issue:  Got an unexpected exception: org.asynchttpclient.exception.RemotelyClosedException: Remotely closed

**Comment by slandelle** [comment]
First, your stacktrace means that the `FullHttpRequest` is being freed after being written, while it's actually already been freed.

I asked you to try to disable retry that because I was wondering if I was recycling the `FullHttpRequest` when retrying (I couldn't check the code at that time). Sadly, no, it's properly being re-created from scratch from the AHC `Request`, see [here](https://github.com/AsyncHttpClient/async-http-client/blob/master/client/src/main/java/org/asynchttpclient/netty/request/NettyRequestSender.java#L433).

So, at this point, I have no what happens.

> Guess my server have random accepting issue
Or that it closes connexions after a while. Only you can tell.

**Comment by slandelle** [comment]
Ok, I was wrong, and the `FullHttpRequest` is indeed recycled, which is wrong when it has a body because it might have been already consumed.

**Comment by slandelle** [comment]
Damn, I was wrong again, `FullHttpRequest` should be recreated...

**Comment by marenzo** [comment]
Tried to create a server that drops the first N requests to somehow reproduce the issue, but with no luck. Need to find out what's special with my server behavior that causes the retry to fail.. Have any ideas?

**Comment by slandelle** [comment]
Nope. Most likely only happens under load.

**Comment by marenzo** [comment]
Any chance you got a chance to look at this issue? I want to get the new AHC 2 to production, but can't until I'm sure all good :)

**Comment by slandelle** [comment]
I'm currently travelling and won't probably be able to take a stab at it before next week.

**Comment by slandelle** [comment]
@marenzo I tried with AHC 2.0.11 and Netty 4.0.40 and haven't been able to reproduce so far...
Could you manage to build a reproducer?

**Comment by marenzo** [comment]
@slandelle I've tried to do so but without much success, I'll try again soon

**Comment by slandelle** [comment]
Cool, thanks

**Comment by jeffpeiyt** [comment]
@marenzo  could you please try an early 2.0 version such as 2.0.0 and if you still can reproduce the issue. We also plan to upgrade from a very old 1.x to 2.0 and want to see if it is stable.

**Comment by slandelle** [comment]
@marenzo gentle ping

**Comment by slandelle** [comment]
This is the same issue as #1265

**Comment by marenzo** [comment]
@slandelle sorry, been myself in a small vacation :)
thanks for the fix!
