### ISSUE TITLE
2 tests are failing

### ISSUE THREAD

**Issue by doom369** [AsyncHttpClient/async-http-client#1229]
```
testAllSequentiallyBecauseNotThreadSafe(org.asynchttpclient.Relative302Test)  Time elapsed: 0.139 sec  <<< FAILURE!
java.lang.AssertionError: expected [404] but found [200]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:389)
	at org.testng.Assert.assertEquals(Assert.java:399)
	at org.asynchttpclient.Relative302Test.redirected302InvalidTest(Relative302Test.java:108)
	at org.asynchttpclient.Relative302Test.testAllSequentiallyBecauseNotThreadSafe(Relative302Test.java:80)

runAllSequentiallyBecauseNotThreadSafe(org.asynchttpclient.PerRequestRelative302Test)  Time elapsed: 0.496 sec  <<< FAILURE!
java.lang.AssertionError: expected [404] but found [200]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:389)
	at org.testng.Assert.assertEquals(Assert.java:399)
	at org.asynchttpclient.PerRequestRelative302Test.redirected302InvalidTest(PerRequestRelative302Test.java:140)
	at org.asynchttpclient.PerRequestRelative302Test.runAllSequentiallyBecauseNotThreadSafe(PerRequestRelative302Test.java:86)
```

**Comment by slandelle** [comment]
I fixed `AsyncStreamHandlerTest` on the 2.1 branch but haven't backported yet (AFK).

**Comment by slandelle** [comment]
After this single fix, build is fine both on my side, and on [Travis](https://travis-ci.org/AsyncHttpClient/async-http-client).

Can you still reproduce?

**Comment by doom369** [comment]
@slandelle 2 still fails.

**Comment by slandelle** [comment]
OK, test is broken/stupid and it fails because you have an HTTP server listening on port 80 on your host.

**Comment by slandelle** [comment]
Fixed, thanks for reporting!
