### ISSUE TITLE
BufferOverflowException thrown when reading response body

### ISSUE THREAD

**Issue by johnou** [AsyncHttpClient/async-http-client#1230]
After updating from async-http-client 1.9.x I have seen a few BufferOverflowExceptions thrown when getResponseBodyAsBytes is invoked.

async-http-client 2.0.11
netty 4.0.40.Final

```java
@Override
public T onCompleted(Response response) throws Exception {
    if (HttpStatus.SC_OK == response.getStatusCode()) {
        byte[] payload = response.getResponseBodyAsBytes(); // **
        try {
            return parseResponseFromJson(payload, clazz);
        } catch (JsonParseException e) {
            logger.error("Failed parsing response " + new String(payload), e);
            return null;
        }
    }
    logger.warn("NOK response: " + response.getResponseBody() + ", status: " + response.getStatusCode());
    return null;
}
```

```noformat
java.nio.BufferOverflowException
	at java.nio.HeapByteBuffer.put(HeapByteBuffer.java:189)
	at java.nio.ByteBuffer.put(ByteBuffer.java:859)
	at org.asynchttpclient.netty.NettyResponse.getResponseBodyAsByteBuffer(NettyResponse.java:180)
	at org.asynchttpclient.netty.NettyResponse.getResponseBodyAsBytes(NettyResponse.java:168)
	at ************.onCompleted(************.java)
	at org.asynchttpclient.AsyncCompletionHandler.onCompleted(AsyncCompletionHandler.java:64)
	at org.asynchttpclient.netty.NettyResponseFuture.getContent(NettyResponseFuture.java:188)
	at org.asynchttpclient.netty.NettyResponseFuture.done(NettyResponseFuture.java:223)
	at org.asynchttpclient.netty.handler.HttpHandler.finishUpdate(HttpHandler.java:58)
	at org.asynchttpclient.netty.handler.HttpHandler.handleChunk(HttpHandler.java:159)
	at org.asynchttpclient.netty.handler.HttpHandler.handleRead(HttpHandler.java:189)
	at org.asynchttpclient.netty.handler.AsyncHttpClientHandler.channelRead(AsyncHttpClientHandler.java:82)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1066)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:900)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:572)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:513)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:427)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:399)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by slandelle** [comment]
o_0
Could you please provide a way to reproduce?

**Comment by johnou** [comment]
I haven't yet managed to create a reproducer, but I ended up looking at org.asynchttpclient.netty.NettyResponse#getResponseBodyAsBytes twice, wouldn't it be safer to read array like this?

```java
public byte[] getResponseBodyAsBytes() {
    ByteBuffer buffer = getResponseBodyAsByteBuffer();
    byte[] response = new byte[buffer.remaining()];
    if (buffer.hasArray()) {
        byte[] array = buffer.array();
        System.arraycopy(array, buffer.arrayOffset() + buffer.position(), response, 0, response.length);
    } else {
        buffer.slice().get(response);
    }
    return response;
}
```

**Comment by johnou** [comment]
While I think that would be a worth while change, the exception was thrown at line 180 which happens before invoking array on the ByteBuffer..

**Comment by slandelle** [comment]
Which `HttpResponseBodyPart` implementation do you use? Eager (default) or lazy?

**Comment by johnou** [comment]
The default, eager.

**Comment by johnou** [comment]
Added full stacktrace of the exception.

**Comment by slandelle** [comment]
> I haven't yet managed to create a reproducer, but I ended up looking at org.asynchttpclient.netty.NettyResponse#getResponseBodyAsBytes twice, wouldn't it be safer to read array like this?

Well, getResponseBodyAsByteBuffer() returns a HeapBuffer that wraps an array with the exact size of the response. So there's no need to do an extra copy like you suggest (as long as we don't change getResponseBodyAsByteBuffer() implementation).

**Comment by slandelle** [comment]
Then, I really fail to see how `getResponseBodyAsByteBuffer()` could crash with the eager implementation, as this one [copies the ByteBuf content into a byte array](https://github.com/AsyncHttpClient/async-http-client/blob/master/client/src/main/java/org/asynchttpclient/netty/EagerResponseBodyPart.java#L40-L48).

**Comment by johnou** [comment]
Only thing I can think of at the moment is that org.asynchttpclient.netty.NettyResponse#bodyParts is modified from another thread while org.asynchttpclient.netty.NettyResponse#getResponseBodyAsByteBuffer is being invoked so length is the incorrect and the second iteration of bodyParts picks up another HttpResponseBodyPart leading to the BufferOverflowException on put.

**Comment by slandelle** [comment]
> Only thing I can think of at the moment is that org.asynchttpclient.netty.NettyResponse#bodyParts is modified from another thread while org.asynchttpclient.netty.NettyResponse#getResponseBodyAsByteBuffer is being invoked so length is the incorrect and the second iteration of bodyParts picks up another HttpResponseBodyPart leading to the BufferOverflowException on put.

But I fail to see how: as you can see from your stacktrace, `getResponseBodyAsByteBuffer` is executed in the `EventLoop`and so is `AsyncHandler.onBodyPartReceived`.

> I will try and find some time early next week to either provide a reproducer or create a custom build with some probes to provide additional information.

Cool, thanks!

**Comment by slandelle** [comment]
Are you sure you're not sharing/reusing `AsyncCompletionHandler` instances?

**Comment by johnou** [comment]
Ouch, the handlers are static..

**Comment by slandelle** [comment]
So that's it :)

`AsyncCompletionHandler` is stateful as it accumulates the response components (status, headers and chunks).
