### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by igouss** [AsyncHttpClient/async-http-client#1266]
```
12:21:58.310 [AsyncHttpClient-5-4] ERROR c.n.c.AbstractCompletionHandler - HTTP Error
java.lang.ArrayIndexOutOfBoundsException: 3
	at java.util.ArrayList.add(ArrayList.java:459)
	at org.asynchttpclient.Response$ResponseBuilder.accumulate(Response.java:193)
	at org.asynchttpclient.AsyncCompletionHandler.onBodyPartReceived(AsyncCompletionHandler.java:39)
	at org.asynchttpclient.filter.AsyncHandlerWrapper.onBodyPartReceived(AsyncHandlerWrapper.java:49)
	at org.asynchttpclient.netty.handler.HttpHandler.updateBodyAndInterrupt(HttpHandler.java:66)
	at org.asynchttpclient.netty.handler.HttpHandler.handleChunk(HttpHandler.java:155)
	at org.asynchttpclient.netty.handler.HttpHandler.handleRead(HttpHandler.java:189)
	at org.asynchttpclient.netty.handler.AsyncHttpClientHandler.channelRead(AsyncHttpClientHandler.java:82)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:147)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by igouss** [comment]
Using org.asynchttpclient:async-http-client:2.1.0-alpha1

**Comment by slandelle** [comment]
Wild guess: you're recycling `AsyncCompletionHandler` instances, or even made it a singleton?

**Comment by igouss** [comment]
Yes, I found a few places where I reuse same handler. This is not advised?

**Comment by slandelle** [comment]
`AsyncHandler`s are stateful. It could be possible to recycle them if you're extra careful (not sure if you would gain anything from the extra complexity in terms of performance though, that's something you'd have to measure).
But you definitely use an instance concurrently from multiple thread at the same time.
