### ISSUE TITLE
RxJava module sporadic test failures

### ISSUE THREAD

**Issue by slandelle** [AsyncHttpClient/async-http-client#1292]
```
testObserveError(org.asynchttpclient.extras.rxjava.AsyncHttpObservableTest)  Time elapsed: 0.643 sec  <<< FAILURE!
java.lang.AssertionError: Not completed!
    at rx.observers.TestSubscriber.assertCompleted(TestSubscriber.java:352)
    at org.asynchttpclient.extras.rxjava.AsyncHttpObservableTest.testObserveError(AsyncHttpObservableTest.java:98)

testObserveMultiple(org.asynchttpclient.extras.rxjava.AsyncHttpObservableTest)  Time elapsed: 0.03 sec  <<< FAILURE!
java.lang.AssertionError: Not completed!
    at rx.observers.TestSubscriber.assertCompleted(TestSubscriber.java:352)
    at org.asynchttpclient.extras.rxjava.AsyncHttpObservableTest.testObserveMultiple(AsyncHttpObservableTest.java:121)

testObserveNoError(org.asynchttpclient.extras.rxjava.AsyncHttpObservableTest)  Time elapsed: 0.007 sec  <<< FAILURE!
java.lang.AssertionError: Not completed!
    at rx.observers.TestSubscriber.assertCompleted(TestSubscriber.java:352)
    at org.asynchttpclient.extras.rxjava.AsyncHttpObservableTest.testObserveNoError(AsyncHttpObservableTest.java:78)

testToObservableError(org.asynchttpclient.extras.rxjava.AsyncHttpObservableTest)  Time elapsed: 0.006 sec  <<< FAILURE!
java.lang.AssertionError: Not completed!
    at rx.observers.TestSubscriber.assertCompleted(TestSubscriber.java:352)
    at org.asynchttpclient.extras.rxjava.AsyncHttpObservableTest.testToObservableError(AsyncHttpObservableTest.java:58)

testToObservableNoError(org.asynchttpclient.extras.rxjava.AsyncHttpObservableTest)  Time elapsed: 0.005 sec  <<< FAILURE!
java.lang.AssertionError: Not completed!
    at rx.observers.TestSubscriber.assertCompleted(TestSubscriber.java:352)
    at org.asynchttpclient.extras.rxjava.AsyncHttpObservableTest.testToObservableNoError(AsyncHttpObservableTest.java:38)

testAbort(org.asynchttpclient.extras.rxjava.single.AsyncHttpSingleTest)  Time elapsed: 0.012 sec  <<< FAILURE!
java.lang.AssertionError: Not completed!
    at rx.observers.TestSubscriber.assertCompleted(TestSubscriber.java:352)
    at org.asynchttpclient.extras.rxjava.single.AsyncHttpSingleTest.testAbort(AsyncHttpSingleTest.java:292)
```

**Comment by slandelle** [comment]
Actually #1310 is not a real fix, but improves error reporting in those tests.
Will reopen if issue happens again and we have more information.
