### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by hirohanin** [AsyncHttpClient/async-http-client#1309]
using ahc 1.9.40

what is being observed that timeout are not necessarily consistent in behavior

is there something wrong in the following

 AsyncHttpClientConfig config = new AsyncHttpClientConfig.Builder()
                .setAllowPoolingConnections(true)
                .setCompressionEnforced(false)
                .setMaxConnections(10)
                .setMaxConnectionsPerHost(10)
                .setRequestTimeout(30)
                .setConnectTimeout(30)
                .setReadTimeout(30)
                .build();

AsyncHttpClient client = new AsyncHttpClient(config);

Request request;
        request = this.client.preparePost("http://myurl".toASCIIString())
                .setBody("blah").setRequestTimeout(30)
                .build();

long d =  System.currentTimeMillis();
Future<String> f = this.client.executeRequest(request, new NingAsyncHandler());
            returnStr = f.get(30, TimeUnit.MILLISECONDS);
System.out.println("Time : "+(System.currentTimeMillis()-d));

I expect a timeout exception everytime 30 ms elapses
but it is not so

**Comment by slandelle** [comment]
Just ran your sample against latest AHC and I get a 30ms timeout (the one from the future) as expected.
AHC1 has reached end of life, please upgrade.

**Comment by hirohanin** [comment]
Apologies for reopening
Moved to 2.0.21
conducted several test to no avail

The intention is to timeout the client after t ms.... which includes time spend in creating a connection, send data over post body and receiving response

**Comment by slandelle** [comment]
I suspect your problem is that there's a bug in your code.
In your sample, you forgot to close the client.

```java
try(AsyncHttpClient client = ???) {

}
```

**Comment by hirohanin** [comment]
Below is the code. Here i wanted to keep timeout as 80ms. the overall timeout. So at least I expect time printed with HERE3 to be less that 81 ms. Am i doing anything wrong. The behaviour i saw that sometimes it times out with messagfe "Request timeout to not-connected after 80 ms"... Sometimes it does not with it printing time > 100 ms with  HERE3 most of the time. Also this is just being used as a standalone application without concurrency

    private AsyncHttpClient client;
    public String post(URI target, byte[] content, int requestTimeoutMillis,
            int maxConnectionPerHost, int maxConnection) throws Exception {
        String returnStr = null;
       long d =  System.currentTimeMillis();
        AsyncHttpClientConfig config = new DefaultAsyncHttpClientConfig.Builder()
                .setKeepAlive(true)
                .setCompressionEnforced(false)
                .setMaxConnections(maxConnection)
                .setMaxConnectionsPerHost(maxConnectionPerHost)
                .setRequestTimeout(80)
                .setFollowRedirect(false)
                .build();
        System.out.println("HERE "+(System.currentTimeMillis()-d));
        this.client = new DefaultAsyncHttpClient(config);
        Request request;
        d =  System.currentTimeMillis();
        request = this.client.preparePost(target.toASCIIString())
                .setBody(content).setRequestTimeout(80)
                .build();
        System.out.println("HERE2 "+(System.currentTimeMillis()-d));
        try {
        	d =  System.currentTimeMillis();
        	Future<String> f = this.client.executeRequest(request, new NingAsyncHandler(this.loggerName));
            returnStr = f.get(80,TimeUnit.MILLISECONDS);
            System.out.println("HERE3 "+(System.currentTimeMillis()-d));
            return returnStr;
        } catch (Exception e) {
        	System.out.println("HERE4 "+(System.currentTimeMillis()-d));
        	e.printStackTrace();
            logger.error(e.getMessage(),e);
            return returnStr;
        }finally{
            this.client.close();
        }   
    }

**Comment by slandelle** [comment]
```java
import static org.asynchttpclient.Dsl.*;

import java.util.concurrent.TimeUnit;

import org.asynchttpclient.AsyncHttpClient;
import org.asynchttpclient.AsyncHttpClientConfig;
import org.asynchttpclient.Request;

public class Test {

    public static void main(String[] args) throws Exception {
        AsyncHttpClientConfig config = config()
                .setRequestTimeout(30)
                .setConnectTimeout(30)
                .setReadTimeout(30)
                .build();

        Request request = post("http://gatling.io").setRequestTimeout(30).build();
        long d = 0;
        try (AsyncHttpClient client = asyncHttpClient(config)) {
            // execute a first request to not measure class loading
            try {
                client.executeRequest(request).get(60, TimeUnit.MILLISECONDS);
            } catch (Exception e) {
                // ignore
            }

            // use nanotime, not currentTimeMillis which is crap
            d = System.nanoTime();
            client.executeRequest(request).get(60, TimeUnit.MILLISECONDS);
        } finally {
            System.out.println("Time : " + ((System.nanoTime() - d) / 1_000_000));
        }
    }
}
```

```
Time : 46
Exception in thread "main" java.util.concurrent.ExecutionException: java.net.ConnectException: connection timed out: gatling.io/192.30.252.153:80
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
	at org.asynchttpclient.netty.NettyResponseFuture.get(NettyResponseFuture.java:165)
	at Test.main(Test.java:26)
Caused by: java.net.ConnectException: connection timed out: gatling.io/192.30.252.153:80
	at org.asynchttpclient.netty.channel.NettyConnectListener.onFailure(NettyConnectListener.java:162)
	at org.asynchttpclient.netty.request.NettyChannelConnector$1.onFailure(NettyChannelConnector.java:103)
	at org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:28)
	at org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:20)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:514)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:507)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:486)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:427)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:129)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:220)
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:120)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:408)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:455)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: gatling.io/192.30.252.153:80
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:218)
	... 7 more
```
