### ISSUE TITLE
PlatformDependent.newAtomicIntegerFieldUpdater does not exist in Netty 4.1.8

### ISSUE THREAD

**Issue by tomjadams** [AsyncHttpClient/async-http-client#1353]
When running (Gatling) against Netty 4.18 get the following error:

```
[error] Uncaught exception when running com.redbubble.perf.scenarios.AppStartup: java.lang.NoSuchMethodError: io.netty.util.internal.PlatformDependent.newAtomicIntegerFieldUpdater(Ljava/lang/Class;Ljava/lang/String;)Ljava/util/concurrent/atomic/AtomicIntegerFieldUpdater;
sbt.ForkMain$ForkError: java.lang.NoSuchMethodError: io.netty.util.internal.PlatformDependent.newAtomicIntegerFieldUpdater(Ljava/lang/Class;Ljava/lang/String;)Ljava/util/concurrent/atomic/AtomicIntegerFieldUpdater;
	at org.asynchttpclient.netty.NettyResponseFuture.<clinit>(NettyResponseFuture.java:52)
	at org.asynchttpclient.netty.request.NettyRequestSender.newNettyResponseFuture(NettyRequestSender.java:311)
	at org.asynchttpclient.netty.request.NettyRequestSender.newNettyRequestAndResponseFuture(NettyRequestSender.java:193)
	at org.asynchttpclient.netty.request.NettyRequestSender.sendRequestWithCertainForceConnect(NettyRequestSender.java:129)
	at org.asynchttpclient.netty.request.NettyRequestSender.sendRequest(NettyRequestSender.java:107)
	at org.asynchttpclient.DefaultAsyncHttpClient.execute(DefaultAsyncHttpClient.java:216)
	at org.asynchttpclient.DefaultAsyncHttpClient.executeRequest(DefaultAsyncHttpClient.java:184)
	at org.asynchttpclient.DefaultAsyncHttpClient.executeRequest(DefaultAsyncHttpClient.java:206)
	at io.gatling.http.ahc.HttpEngine.warmpUp(HttpEngine.scala:96)
	at io.gatling.http.protocol.HttpProtocol$$anon$1.$anonfun$newComponents$1(HttpProtocol.scala:62)
	at io.gatling.http.protocol.HttpProtocol$$anon$1$$Lambda$348/814641027.apply(Unknown Source)
	at io.gatling.core.protocol.ProtocolComponentsRegistry.comps$1(Protocol.scala:67)
	at io.gatling.core.protocol.ProtocolComponentsRegistry.$anonfun$components$4(Protocol.scala:69)
	at io.gatling.core.protocol.ProtocolComponentsRegistry$$Lambda$322/1065376160.apply(Unknown Source)
	at scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:79)
	at io.gatling.core.protocol.ProtocolComponentsRegistry.components(Protocol.scala:69)
	at io.gatling.http.action.HttpActionBuilder.lookUpHttpComponents(HttpActionBuilder.scala:25)
	at io.gatling.http.action.sync.HttpRequestActionBuilder.build(HttpRequestActionBuilder.scala:33)
	at io.gatling.core.structure.StructureBuilder.$anonfun$build$1(StructureBuilder.scala:34)
	at io.gatling.core.structure.StructureBuilder$$Lambda$319/1236870787.apply(Unknown Source)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
	at scala.collection.immutable.List.foldLeft(List.scala:86)
	at io.gatling.core.structure.StructureBuilder.build(StructureBuilder.scala:33)
	at io.gatling.core.structure.StructureBuilder.build$(StructureBuilder.scala:32)
	at io.gatling.core.structure.ScenarioBuilder.build(ScenarioBuilder.scala:38)
	at io.gatling.core.structure.PopulationBuilder.build(ScenarioBuilder.scala:98)
	at io.gatling.core.scenario.SimulationParams.$anonfun$scenarios$1(Simulation.scala:188)
	at io.gatling.core.scenario.SimulationParams$$Lambda$317/433288346.apply(Unknown Source)
	at scala.collection.immutable.List.map(List.scala:272)
	at io.gatling.core.scenario.SimulationParams.scenarios(Simulation.scala:188)
	at io.gatling.app.Runner.run0(Runner.scala:95)
	at io.gatling.app.Runner.run(Runner.scala:64)
	at io.gatling.app.Gatling$.start(Gatling.scala:56)
	at io.gatling.app.Gatling$.fromArgs(Gatling.scala:41)
	at io.gatling.sbt.GatlingTask.liftedTree1$1(GatlingTask.scala:51)
	at io.gatling.sbt.GatlingTask.execute(GatlingTask.scala:50)
	at sbt.ForkMain$Run$2.call(ForkMain.java:296)
	at sbt.ForkMain$Run$2.call(ForkMain.java:286)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

This is when using Gatling, any of the recent versions, including 2.1.0-alpha4 & 2.1.28.

**Comment by slandelle** [comment]
Gatling is not compatible with AHC2.1/Netty 4.1 atm.
Generally speaking, you're not supposed to change the AHC or Netty versions that Gatling ships.

**Comment by tomjadams** [comment]
@slandelle Does Gatlin run at all on Scala 2.12? With 2.2.3 I get:

```
[error] Modules were resolved with conflicting cross-version suffixes in {file:/Users/tom/src/ios-api/app/}perf:
[error]    org.scala-lang.modules:scala-xml _2.12, _2.11
[error]    org.scala-lang.modules:scala-java8-compat _2.12, _2.11
[error]    org.scala-lang.modules:scala-parser-combinators _2.12, _2.11
```

I can't get it to build by doing the following in `build.sbt`:

```
lazy val gattlingHighCharts = ("io.gatling.highcharts" % "gatling-charts-highcharts" % gattlingVersion % "it,test")
    .excludeAll(ExclusionRule("org.scala-lang.modules", "scala-xml_2.11"))
    .excludeAll(ExclusionRule("org.scala-lang.modules", "scala-java8-compat_2.11"))
    .excludeAll(ExclusionRule("org.scala-lang.modules", "scala-parser-combinators_2.11"))
lazy val gattlingTest = ("io.gatling" % "gatling-test-framework" % gattlingVersion % "it,test")
    .excludeAll(ExclusionRule("org.scala-lang.modules", "scala-xml_2.11"))
    .excludeAll(ExclusionRule("org.scala-lang.modules", "scala-java8-compat_2.11"))
    .excludeAll(ExclusionRule("org.scala-lang.modules", "scala-parser-combinators_2.11"))
```

But it fails with:

```
[error] Uncaught exception when running tests: java.lang.NoSuchMethodError: scala.Predef$.refArrayOps([Ljava/lang/Object;)Lscala/collection/mutable/ArrayOps;
sbt.ForkMain$ForkError: java.lang.NoSuchMethodError: scala.Predef$.refArrayOps([Ljava/lang/Object;)Lscala/collection/mutable/ArrayOps;
	at io.gatling.sbt.GatlingRunner.tasks(GatlingRunner.scala:30)
	at sbt.ForkMain$Run.runTests(ForkMain.java:253)
	at sbt.ForkMain$Run.run(ForkMain.java:139)
	at sbt.ForkMain.main(ForkMain.java:121)
```

Happy to move this to the Gatling issue tracker if that's better.

**Comment by tomjadams** [comment]
With "3.0.0-SNAPSHOT" I get the original error.
