### ISSUE TITLE
Race condition in the BodyDeferringAsyncHandler example

### ISSUE THREAD

**Issue by dremon** [AsyncHttpClient/async-http-client#1451]
This code shown as an example is actually incorrect:
```
     PipedOutputStream pout = new PipedOutputStream();
     BodyDeferringAsyncHandler bdah = new BodyDeferringAsyncHandler(pout);
     // client executes async
     Future<Response> fr = client.prepareGet("http://foo.com/aresource").execute(bdah);
     // main thread will block here until headers are available
     Response response = bdah.getResponse();
     if (response.getStatusCode() == 200) {
      InputStream pin = new BodyDeferringInputStream(fr,new PipedInputStream(pout));
      // consume InputStream
      ...
     } else {
      // handle unexpected response status code
      ...
     }
```

The reason is that the bdah.getResponse might write into the pout channel which is not connected yet.
This has been observed in the tests.
I think a better code would be:

```
     PipedOutputStream pout = new PipedOutputStream();
     BodyDeferringAsyncHandler bdah = new BodyDeferringAsyncHandler(pout);
     // client executes async
     Future<Response> fr = client.prepareGet("http://foo.com/aresource").execute(bdah);

     InputStream pin = new BodyDeferringInputStream(fr,new PipedInputStream(pout));

     // main thread will block here until headers are available
     Response response = bdah.getResponse();
     if (response.getStatusCode() == 200) {
      // consume pin
      ...
     } else {
      // handle unexpected response status code
      ...
     }
```

**Comment by slandelle** [comment]
> This has been observed in the tests.

Which test are you referring to? Could you please provide a failing test that proves the suggested fix?

**Comment by dremon** [comment]
[async-test.zip](https://github.com/AsyncHttpClient/async-http-client/files/1221393/async-test.zip)

I have attached a sample Scala/Gradle project, can be run with "./gradlew run"
There are two tests run, the bad one (from example) either hangs or dumps the following stack:

```
java.io.IOException: java.io.IOException: Pipe not connected
        at org.asynchttpclient.handler.BodyDeferringAsyncHandler$BodyDeferringInputStream.close(BodyDeferringAsyncHandler.java:265)
        at com.test.DeferTest$$anon$1.close(DeferTest.scala:27)
        at resource.MediumPriorityResourceImplicits$$anon$3.close(Resource.scala:82)
        at resource.MediumPriorityResourceImplicits$$anon$3.close(Resource.scala:81)
        at resource.DefaultManagedResource.unsafeClose(AbstractManagedResource.scala:116)
        at resource.AbstractManagedResource.$anonfun$acquireFor$2(AbstractManagedResource.scala:89)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.util.control.Exception$Catch.$anonfun$either$1(Exception.scala:248)
        at scala.util.control.Exception$Catch.apply(Exception.scala:224)
        at scala.util.control.Exception$Catch.either(Exception.scala:248)
        at resource.AbstractManagedResource.acquireFor(AbstractManagedResource.scala:89)
        at resource.ManagedResourceOperations.apply(ManagedResourceOperations.scala:26)
        at resource.ManagedResourceOperations.apply$(ManagedResourceOperations.scala:26)
        at resource.AbstractManagedResource.apply(AbstractManagedResource.scala:50)
        at resource.ManagedResourceOperations.acquireAndGet(ManagedResourceOperations.scala:25)
        at resource.ManagedResourceOperations.acquireAndGet$(ManagedResourceOperations.scala:25)
        at resource.AbstractManagedResource.acquireAndGet(AbstractManagedResource.scala:50)
        at com.test.DeferTest$.main(DeferTest.scala:78)
        at com.test.DeferTest.main(DeferTest.scala)
Caused by: java.io.IOException: Pipe not connected
        at java.io.PipedOutputStream.write(PipedOutputStream.java:140)
        at java.io.OutputStream.write(OutputStream.java:75)
        at org.asynchttpclient.handler.BodyDeferringAsyncHandler.onBodyPartReceived(BodyDeferringAsyncHandler.java:154)
        at org.asynchttpclient.netty.handler.HttpHandler.handleChunk(HttpHandler.java:115)
        at org.asynchttpclient.netty.handler.HttpHandler.handleRead(HttpHandler.java:149)
        at org.asynchttpclient.netty.handler.AsyncHttpClientHandler.channelRead(AsyncHttpClientHandler.java:76)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1342)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:934)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by slandelle** [comment]
Thanks!
