### ISSUE TITLE
NPE after upgrading to 2.0.37

### ISSUE THREAD

**Issue by StarWindMoonCloud** [AsyncHttpClient/async-http-client#1483]
Below is the detail stack, when trying to convert to java CompletableFuture, anyone has more clues?
```
java.util.concurrent.CompletionException: java.lang.NullPointerException
       	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
       	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
       	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)
       	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
       	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
       	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
       	at com.pm.push.offline.utils.IOUtil$1.onCompleted(IOUtil.java:36)
       	at com.pm.push.offline.utils.IOUtil$1.onCompleted(IOUtil.java:33)
       	at org.asynchttpclient.AsyncCompletionHandler.onCompleted(AsyncCompletionHandler.java:64)
       	at org.asynchttpclient.netty.NettyResponseFuture.getContent(NettyResponseFuture.java:193)
       	at org.asynchttpclient.netty.NettyResponseFuture.done(NettyResponseFuture.java:227)
       	at org.asynchttpclient.netty.handler.HttpHandler.finishUpdate(HttpHandler.java:59)
       	at org.asynchttpclient.netty.handler.HttpHandler.handleChunk(HttpHandler.java:161)
       	at org.asynchttpclient.netty.handler.HttpHandler.handleRead(HttpHandler.java:189)
       	at org.asynchttpclient.netty.handler.AsyncHttpClientHandler.channelRead(AsyncHttpClientHandler.java:76)
       	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
       	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
       	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
       	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
       	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
       	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
       	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
       	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
       	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
       	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
       	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
       	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
       	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:312)
       	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:286)
       	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
       	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
       	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
       	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
       	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1302)
       	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
       	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
       	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
       	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
       	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:646)
       	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:581)
       	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498)
       	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460)
       	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131)
       	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
       	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
```

**Comment by slandelle** [comment]
You have a NPE and didn't provide its stacktrace. How could one tell?

**Comment by slandelle** [comment]
Then, could you please upgrade to AHC 2.1.0-RC1 and report if issue can still be reproduced?

**Comment by StarWindMoonCloud** [comment]
@slandelle stacktrace was in comment, what else did you mean?
I'm trying 2.1.0-RC1, but could you help point out any specific changes that may matter

**Comment by slandelle** [comment]
@StarWindMoonCloud The stacktrace you provided only shows the wrapping exception, not the cause:
```
Caused by: java.lang.NullPointerException
MISSING STACKTRACE of this NPE!!!
```

Also, please provide a way to reproduce your issue.

**Comment by StarWindMoonCloud** [comment]
I know, java 8 completable future dropped the stack unfortunately, have to add extra logic to dig out the reason

**Comment by slandelle** [comment]
Otherwise, please provide a reproducer and I'll be able to dig myself.

**Comment by StarWindMoonCloud** [comment]
I'll try first, will let you know if further help needed, thanks @slandelle

**Comment by StarWindMoonCloud** [comment]
Resolved the problem, it's actually some exception when processing http response, which was cascaded by java completable future, and it didn't keep the stack.
Thank you all the same @slandelle
