### ISSUE TITLE
Exceptions when trying to use hosts in the /etc/hosts file when running unit tests

### ISSUE THREAD

**Issue by nddipiazza** [AsyncHttpClient/async-http-client#1581]
I'm having an issue here. I'm trying to add a PR to allow users to specify the keytab and principalName for Spnego so they can have multiple spnego auth on the same JVM.

I have a `/etc/hosts` file entry:

`192.168.1.155   win-qbfsb933r5p`

I can normally simply run the following:

```
import java.net.InetAddress;

public class Test {
  public static void main(String [] args) throws Exception {
    InetAddress.getByName("win-qbfsb933r5p");
  }
}
```

When I run this withint he testNG unit tests with async http client, I get an error:

```
@Test
  public void testHostLookup() throws Exception {
    InetAddress.getByName("win-qbfsb933r5p");
  }
```

```

java.net.UnknownHostException: DNS name not found [response code 3]

	at sun.net.spi.nameservice.dns.DNSNameService.resolve(DNSNameService.java:180)
	at sun.net.spi.nameservice.dns.DNSNameService.lookupAllHostAddr(DNSNameService.java:351)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at java.net.InetAddress.getByName(InetAddress.java:1076)
	at org.asynchttpclient.MyTest.testHostLookup(SpnegoTest.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
```

Why is that?

**Comment by nddipiazza** [comment]
Hi @slandelle i cannot seem to figure out why I cannot use my `/etc/hosts` file when building unit tests for AHC. Is there something within that makes a static change possibly? 

I agree it is core java related, but it is the classpath of the AHC that seems to show the issue. A standalone java app on same system does not have the problem. Any idea why that might be?

**Comment by nddipiazza** [comment]
i'll see if i can just build my test outside of the AHC test package - it's not like i could check in a test that relied on real hosts and host files anyway s
