### ISSUE TITLE
Retrofit module: http client supplier is not invoked, resulting in NPE

### ISSUE THREAD

**Issue by bfg** [AsyncHttpClient/async-http-client#1616]
PR #1615 introduced `Supplier<AsyncHttpClient>` to retrieve HTTP client instance to execute HTTP request, but it's never called because `getHttpClient()` is not invoked at `Call` creation procedure. This results in NPE if concrete `AsyncHttpClient` instance is not set.

```
java.lang.NullPointerException: httpClient
        at org.asynchttpclient.extras.retrofit.AsyncHttpClientCall.<init>(AsyncHttpClientCall.java:39)
        at org.asynchttpclient.extras.retrofit.AsyncHttpClientCall$AsyncHttpClientCallBuilder.build(AsyncHttpClientCall.java:39)
        at org.asynchttpclient.extras.retrofit.AsyncHttpClientCallFactory.newCall(AsyncHttpClientCallFactory.java:63)
        at com.example.retrofit.CallFactoryRegistry.lambda$getComposite$0(CallFactoryRegistry.java:32)
        at retrofit2.OkHttpCall.createRawCall(OkHttpCall.java:190)
        at retrofit2.OkHttpCall.enqueue(OkHttpCall.java:100)
        at retrofit2.adapter.rxjava.CallEnqueueOnSubscribe.call(CallEnqueueOnSubscribe.java:39)
        at retrofit2.adapter.rxjava.CallEnqueueOnSubscribe.call(CallEnqueueOnSubscribe.java:25)
        at retrofit2.adapter.rxjava.BodyOnSubscribe.call(BodyOnSubscribe.java:36)
        at retrofit2.adapter.rxjava.BodyOnSubscribe.call(BodyOnSubscribe.java:28)
```

I'll submit PR.

**Comment by slandelle** [comment]
Please do!
