### ISSUE TITLE
java.util.concurrent.TimeoutException request Timeout

### ISSUE THREAD

**Issue by smileMrLee** [AsyncHttpClient/async-http-client#1630]
There is cause detail info, how can I  resolve it!  thx!
mac 10.14.2
java 1.8

## caused by
```
19:15:05.797 [main] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.machineId: 38:f9:d3:ff:fe:64:0e:20 (auto-detected)
Caused by: java.util.concurrent.TimeoutException: Request timeout to api.map.baidu.com:80 after 3000 ms
	at org.asynchttpclient.netty.timeout.TimeoutTimerTask.expire(TimeoutTimerTask.java:43)
	at org.asynchttpclient.netty.timeout.RequestTimeoutTimerTask.run(RequestTimeoutTimerTask.java:50)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:668)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:743)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:471)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
19:15:05.857 [AsyncHttpClient-3-1] DEBUG io.netty.buffer.AbstractByteBuf - -Dio.netty.buffer.bytebuf.checkAccessible: true
19:15:05.857 [AsyncHttpClient-3-1] DEBUG io.netty.util.ResourceLeakDetectorFactory - Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@67ceb7ff
19:15:05.949 [AsyncHttpClient-3-1] DEBUG org.asynchttpclient.netty.handler.HttpHandler - Channel Closed: [id: 0xa92bfeb6, L:0.0.0.0/0.0.0.0:64571 ! R:api.map.baidu.com/180.97.93.23:80] with attribute null
```

### more debug info

```
19:15:03.781 [AsyncHttpClient-timer-1-1] DEBUG org.asynchttpclient.netty.timeout.TimeoutTimerTask - Request timeout to api.map.baidu.com:80 after 3000 ms for NettyResponseFuture{currentRetry=0,
	isDone=0,
	isCancelled=0,
	asyncHandler=com.caocao.poi.collector.http.AsyncHttpUtil$AsynHttpComHandler@55a4301b,
	nettyRequest=org.asynchttpclient.netty.request.NettyRequest@5a2d59ac,
	future=java.util.concurrent.CompletableFuture@25151e7b[Not completed],
	uri=http://api.map.baidu.com/parking/search?ak=osGmL******KWXE4CBvYjByuNCta&location=116.313064,40.048541&coordtype=gcj02ll,
	keepAlive=true,
	redirectCount=0,
	timeoutsHolder=org.asynchttpclient.netty.timeout.TimeoutsHolder@5cf888c1,
	inAuth=0,
	statusReceived=0,
	touch=1556277300741} after 3044 ms
19:15:03.782 [AsyncHttpClient-timer-1-1] DEBUG org.asynchttpclient.netty.request.NettyRequestSender - Aborting Future NettyResponseFuture{currentRetry=0,
	isDone=0,
	isCancelled=0,
	asyncHandler=com.caocao.poi.collector.http.AsyncHttpUtil$AsynHttpComHandler@55a4301b,
	nettyRequest=org.asynchttpclient.netty.request.NettyRequest@5a2d59ac,
	future=java.util.concurrent.CompletableFuture@25151e7b[Not completed],
	uri=http://api.map.baidu.com/parking/search?ak=osGmL*****KWXrliE4CBvYjByuNCta&location=116.313064,40.048541&coordtype=gcj02ll,
	keepAlive=true,
	redirectCount=0,
	timeoutsHolder=org.asynchttpclient.netty.timeout.TimeoutsHolder@5cf888c1,
	inAuth=0,
	statusReceived=0,
	touch=1556277300741}
```
### my code
```
public static AsyncHttpClient asyncHttpClient = Dsl.asyncHttpClient(Dsl.config()
            .setMaxConnections(2000)
            .setMaxConnectionsPerHost(2000)
            .setPooledConnectionIdleTimeout(1000)
            .setConnectionTtl(500)
            .setIoThreadsCount(200)
            .setConnectTimeout(3000)
            .setReadTimeout(3000)
            .setRequestTimeout(3000)
            .setUseNativeTransport(System.getProperty("os.name").toLowerCase().indexOf("linux") > 0).build());
```
when  'setRequestTimeout(30000)' , it's work ok!
but my colleagues execute same code，it's well!

**Comment by slandelle** [comment]
It’s not an issue, it’s the request timeout you’ve configured that triggers because your server didn’t respond in due time.
