### ISSUE TITLE
Too many connections even though the client re-used in flux

### ISSUE THREAD

**Issue by bagdemir** [AsyncHttpClient/async-http-client#1637]
I am having too many connections exception, even though I reuse the client and create unbound requests:

```
  public void start() {
    var httpClientConfig = Dsl.config()
        .setConnectTimeout(500)
        .setMaxConnections(20)
        .setKeepAlive(true)
        .setMaxConnectionsPerHost(10)
        .build();

    var httpClient = Dsl.asyncHttpClient(httpClientConfig);

    this.subscribe = Flux.fromStream(<Streaming users>)
        .take(duration)
        .doOnTerminate(this::notifyAwaiting)
        .flatMap(user -> Flux.fromStream(simulation.getSpecs().stream())
            .filter(s -> s instanceof HttpSpec)
            .map(s -> (HttpSpec) s)
            .flatMap(spec -> materializeWith(httpClient, user, spec)
                .doOnSuccess(r -> System.out.println(r.getStatusCode()))
                .doOnError(t -> System.err.println(t.getMessage()))))
        .subscribe(this::dispatch);

    await();
    stop();
  }
  private Mono<Response> materializeWith(final AsyncHttpClient httpClient,
      final UserSession userSession,
      final HttpSpec httpSpec) {

    Objects.requireNonNull(httpSpec);

    var requestBuilder = getRequestBuilder(httpSpec);
    httpSpec.getHeaders().forEach(requestBuilder::addHeader);
    httpSpec.getQueryParameters().forEach(requestBuilder::addQueryParam);
    setAuthToken(userSession, requestBuilder);
    var listenableFuture = httpClient.executeRequest(requestBuilder.build());

    listenableFuture.addListener(() -> {

      try {
        Response response = listenableFuture.get();
        System.out.println(response.getStatusCode());
      } catch (InterruptedException e) {
        e.printStackTrace();
      } catch (ExecutionException e) {
        e.printStackTrace();
      }

    }, null);

    return Mono.fromCompletionStage(listenableFuture.toCompletableFuture());
  }
```
Here is the exception stacktrace:
```
java.util.concurrent.ExecutionException: org.asynchttpclient.exception.TooManyConnectionsPerHostException: Too many connections: 10
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
	at org.asynchttpclient.netty.NettyResponseFuture.get(NettyResponseFuture.java:201)
	at io.ryos.rhino.sdk.runners.ReactiveSimulationRunner.lambda$materializeWith$6(ReactiveSimulationRunner.java:117)
	at org.asynchttpclient.netty.NettyResponseFuture.lambda$addListener$0(NettyResponseFuture.java:294)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:886)
	at java.base/java.util.concurrent.CompletableFuture.whenCompleteAsync(CompletableFuture.java:2261)
	at org.asynchttpclient.netty.NettyResponseFuture.addListener(NettyResponseFuture.java:294)
```

**Comment by namiles** [comment]
We can't tell you anything about this without knowing how fast you're consuming the Flux since you didn't send us `dispatch()`. It sounds like the answer is "too fast" and that you're blowing your own limit. This sounds like a problem with your code.

If you think this is a problem with AHC, please post a minimal working example (not snippets) showing the issue.
