### ISSUE TITLE
Hanging thread even though async client is closed

### ISSUE THREAD

**Issue by hejcz** [AsyncHttpClient/async-http-client#1648]
Hello,

Following application never ends due to:

```
"ObjectCleanerThread" #15 prio=1 os_prio=0 cpu=0,19ms elapsed=10,61s tid=0x00007faca0907000 nid=0x18c0 in Object.wait()  [0x00007fac59745000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(java.base@11.0.3/Native Method)
	- waiting on <0x00000007148f9a18> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(java.base@11.0.3/ReferenceQueue.java:155)
	- waiting to re-lock in wait() <0x00000007148f9a18> (a java.lang.ref.ReferenceQueue$Lock)
	at io.netty.util.internal.ObjectCleaner$1.run(ObjectCleaner.java:52)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(java.base@11.0.3/Thread.java:834)
```

```java
package io.github.hejcz;

import org.asynchttpclient.AsyncHttpClient;
import org.asynchttpclient.Dsl;

import java.io.IOException;

public class App4 {

    public static void main(String[] args) {
        try (AsyncHttpClient client = Dsl.asyncHttpClient()) {
            client.executeRequest(Dsl.get("http://google.com").build());
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

}
```

It was run on Java 11.

**Comment by slandelle** [comment]
AHC version?

**Comment by hejcz** [comment]
2.2.0 issue does not exist in 2.10.1. Thank you!
