### ISSUE TITLE
AsyncHttpClient creates too many AsyncHttpClient-timer threads

### ISSUE THREAD

**Issue by myakovets** [AsyncHttpClient/async-http-client#1658]
I am using AsyncHttpClient 2.3.0 and Default configuration.

I've noticed that AHC created two types of threads (from the thread dump):

1)

```
AsyncHttpClient-timer-478-1" - Thread t@30390    java.lang.Thread.State: TIMED_WAITING
        at java.lang.Thread.$$YJP$$sleep(Native Method)
        at java.lang.Thread.sleep(Thread.java)
        at io.netty.util.HashedWheelTimer$Worker.waitForNextTick(HashedWheelTimer.java:560)
        at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:459)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
```
2)
```
AsyncHttpClient-3-4" - Thread t@20320    java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.EPollArrayWrapper.$$YJP$$epollWait(Native Method)
        at sun.nio.ch.EPollArrayWrapper.epollWait(EPollArrayWrapper.java)
        at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
        at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
        - locked <16163575> (a io.netty.channel.nio.SelectedSelectionKeySet)
        - locked <49280039> (a java.util.Collections$UnmodifiableSet)
        - locked <2decd496> (a sun.nio.ch.EPollSelectorImpl)
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
        at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
        at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:753)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:409)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
```
I've expected that AsyncHttpClient uses a few threads under the hood. But after a few days of running, AsyncHttpClient creates ~500 of AsyncHttpClient-timer-xxx-x threads and a few AsyncHttpClient-x-x. It's called not very intensively, probably also ~500 times per this period. Only executeRequest is used (execute request and get on returned future) https://static.javadoc.io/org.asynchttpclient/async-http-client/2.3.0/org/asynchttpclient/AsyncHttpClient.html#executeRequest-org.asynchttpclient.Request-org.asynchttpclient.AsyncHandler-:

`<T> ListenableFuture<T> executeRequest(Request request, AsyncHandler<T> handler);`

I've seen a page about connection pool configuration (https://github.com/AsyncHttpClient/async-http-client/wiki/Connection-pooling) but nothing about thread pool configuration.

What is the difference between both types of thread and what can cause a large number of threads created? Is there any configuration I should apply?

**Comment by slandelle** [comment]
You’re most likely creating one AHC instance per request, which is very bad, and not closing them, which is even worse.

**Comment by myakovets** [comment]
Hmm... does not seem so. It's a field of a Singleton.

Strange that I cannot reproduce it's locally. I have an opposite picture: only one AsyncHttpClient-timer and new AsyncHttpClient-x-x thread per call (if calls one after another new thread is not created).

What is the difference between AsyncHttpClient-x-x and AsyncHttpClient-timer treads? Can Connection Pool config help?

**Comment by slandelle** [comment]
AsyncHttpClient-x-x: I/O (twice number of cores)
AsyncHttpClient-timer: timer for timeouts (only one)

Any different number means you’re creating multiple clients.

**Comment by latharavishankar** [comment]
We have a process that sends Metrics every minute to a HTTP Server. We use the AsyncHttpClient to send them. What is a better thing to do - 
1. Create an AsyncHttpClient every minute, use it and close it then?
2. Create an instance of AsyncHttpClient at init(), and keep it around. In this case I have noticed that the number of threads goes to what is mentioned - 
AsyncHttpClient-x-x: I/O (twice number of cores)
AsyncHttpClient-timer: timer for timeouts (only one)

**Comment by latharavishankar** [comment]
After reading this - https://github.com/AsyncHttpClient/async-http-client#client, it seems like it is best to have a global instance and reuse it for requests, rather than closing and creating the client.
Also, seems to me that, it is OK to have thread created (AsyncHttpClient-x-x: I/O (twice number of cores)
AsyncHttpClient-timer: timer for timeouts (only one)).
Back to my question then - 
Also what does it do with so many threads? Is it OK to reduce it by calling - DefaultAsyncHttpClientConfig.Builder().setIoThreadsCount()
