### ISSUE TITLE
RequestTimeOut closes the channel

### ISSUE THREAD

**Issue by pinankg** [AsyncHttpClient/async-http-client#1692]
Is there a way to "not" close the channel when the request-time-out occurs?

e.g.
https://github.com/AsyncHttpClient/async-http-client/blob/master/client/src/main/java/org/asynchttpclient/netty/request/NettyRequestSender.java#L465-L467
It results in the channel being closed. I intend to keep the channel (connection) alive (in cases of requestTimeOut), as I am trying to use mutual-TLS and the handshake is quite expensive (as compared to TLS).

Here's a stacktrace:
```java
java.util.concurrent.TimeoutException: Request timed out to MY_SERVER/MY_IP_ADDRESS:443 of 50 ms
	at com.ning.http.client.providers.netty.request.timeout.TimeoutTimerTask.expire(TimeoutTimerTask.java:47) ~[async-http-client-1.9.40.jar:na]
	at com.ning.http.client.providers.netty.request.timeout.RequestTimeoutTimerTask.run(RequestTimeoutTimerTask.java:48) ~[async-http-client-1.9.40.jar:na]
	at org.jboss.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:556) ~[netty-3.10.6.Final.jar:na]
	at org.jboss.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:632) ~[netty-3.10.6.Final.jar:na]
	at org.jboss.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:369) ~[netty-3.10.6.Final.jar:na]
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) ~[netty-3.10.6.Final.jar:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
```

The `NettyRequestSender` is `final` so I couldn't find a way to extend it (to override the `abort` method)

Thanks!

**Comment by slandelle** [comment]
First, you're using AHC 1 which has been dead for several years now. No additional work will ever happen there.

Then, wanting to keep the connection alive after a timeout is completely wrong: you'll end up trying to use the socket for a new request and receive unrelated segments from the previous one.
What you're need is to increase the TLS handshake timeout: https://github.com/AsyncHttpClient/async-http-client/blob/master/client/src/main/java/org/asynchttpclient/DefaultAsyncHttpClientConfig.java#L1042

**Comment by pinankg** [comment]
Thanks a lot slandelle! It makes sense now why the connection should be closed on RequestTimeOuts.
