### ISSUE TITLE
SpnegoEngineTest#testGetCompleteServicePrincipalName test failed in master branch

### ISSUE THREAD

**Issue by zagorulkinde** [AsyncHttpClient/async-http-client#1706]
org.asynchttpclient.spnego.SpnegoEngineTest#testGetCompleteServicePrincipalName failed

```
java.lang.AssertionError: did not expect [HTTP@localhost] but found [HTTP@localhost]

	at org.testng.Assert.fail(Assert.java:97)
	at org.testng.Assert.assertNotEquals(Assert.java:1399)
	at org.testng.Assert.assertNotEquals(Assert.java:1404)
	at org.asynchttpclient.spnego.SpnegoEngineTest.testGetCompleteServicePrincipalName(SpnegoEngineTest.java:138)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.testng.TestRunner.privateRun(TestRunner.java:766)
	at org.testng.TestRunner.run(TestRunner.java:587)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
	at org.testng.TestNG.runSuites(TestNG.java:1039)
	at org.testng.TestNG.run(TestNG.java:1007)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
```

**Comment by slandelle** [comment]
Hilarious.

`InetAddress.getByName("localhost").getCanonicalHostName()` return `127.0.0.1` with JDK8 and `localhost` with JDK11.
I would say JDK8 behaviour is wrong, but then, I have no idea what the expected behavior in the context of Spenego is.

**Comment by TomGranot** [comment]
I'm wondering whether testing against different JDKs is worth the effort here. Or in general...
