### ISSUE TITLE
org.asynchttpclient.uri.Uri.create() cannot handle ipV6 address properly

### ISSUE THREAD

**Issue by Huan9** [AsyncHttpClient/async-http-client#1725]
If try to create Uri using ipV6 address, like below:
Uri.create("https://0:0:0:0:0:0:0:1:61700") will get below error, seem like the org.asynchttpclient.uri.UriParser.computeRegularHostPort will always assume the pass in url string is either ipv4 address or just hostname.

java.lang.NumberFormatException: For input string: "0:0:0:0:0:0:1:61584"

	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.asynchttpclient.uri.UriParser.computeRegularHostPort(UriParser.java:216)
	at org.asynchttpclient.uri.UriParser.parseAuthority(UriParser.java:299)
	at org.asynchttpclient.uri.UriParser.parse(UriParser.java:358)
	at org.asynchttpclient.uri.Uri.create(Uri.java:67)
	at org.asynchttpclient.uri.Uri.create(Uri.java:62)

**Comment by slandelle** [comment]
Thanks for reporting.
Would you be willing to contribute a fix?

**Comment by slandelle** [comment]
Actually, your url is wrong. IPv6 addresses must be wrapped with square braces:

`Uri.create("https://[0:0:0:0:0:0:0:0:1]:61700")`
