### ISSUE TITLE
Graal native-image support?

### ISSUE THREAD

**Issue by pshirshov** [AsyncHttpClient/async-http-client#1733]
In case I build an app using `async-http-client` with `native-image` I'm getting an error ` java.lang.ExceptionInInitializerError: null` while trying to call `org.asynchttpclient.Dsl.asyncHttpClient()`.

Seems like something is wrong with static initializers/static fields somewhere in `async-http-client`

Native images aren't that great in diagnostics so I can't provide more details at the moment. Also I have this in `native-image` commandline: `--initialize-at-run-time=org.asynchttpclient`

added:

The stacktrace is:

```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:290)
	at java.lang.Class.ensureInitialized(DynamicHub.java:499)
	at org.asynchttpclient.DefaultAsyncHttpClientConfig$Builder.<init>(DefaultAsyncHttpClientConfig.java:669)
	at org.asynchttpclient.DefaultAsyncHttpClient.<init>(DefaultAsyncHttpClient.java:71)
	at org.asynchttpclient.Dsl.asyncHttpClient(Dsl.java:28)
        ...
Caused by: java.lang.NullPointerException: inStream parameter is null
	at java.util.Objects.requireNonNull(Objects.java:246)
	at java.util.Properties.load(Properties.java:403)
	at org.asynchttpclient.config.AsyncHttpClientConfigDefaults.<clinit>(AsyncHttpClientConfigDefaults.java:79)
	at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:350)
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:270)
```

Apparently something is wrong with static initializer in https://github.com/AsyncHttpClient/async-http-client/blob/d4f1e5835b81a5e813033ba2a64a07b020c70007/client/src/main/java/org/asynchttpclient/config/AsyncHttpClientConfigDefaults.java#L80

**Comment by pshirshov** [comment]
Solved by copying missing resources, seems to be fine now.
