### ISSUE TITLE
Can't write request  java.lang.NullPointerException

### ISSUE THREAD

**Issue by chenjinkai** [AsyncHttpClient/async-http-client#1734]
hi:
  The following exception was caught without other exceptions. We don't know why this exception happened. 
 Can help avoid this exception in a better way？

the client version is 1.9.39. 

`Can't write request
java.lang.NullPointerException
	at com.ning.http.client.providers.netty.future.NettyResponseFuture.getChannelRemoteAddress(NettyResponseFuture.java:407)
	at com.ning.http.client.providers.netty.request.timeout.TimeoutTimerTask.<init>(TimeoutTimerTask.java:41)
	at com.ning.http.client.providers.netty.request.timeout.RequestTimeoutTimerTask.<init>(RequestTimeoutTimerTask.java:31)
	at com.ning.http.client.providers.netty.request.NettyRequestSender.scheduleTimeouts(NettyRequestSender.java:395)
	at com.ning.http.client.providers.netty.request.NettyRequestSender.writeRequest(NettyRequestSender.java:341)
	at com.ning.http.client.providers.netty.request.NettyRequestSender.sendRequestWithCachedChannel(NettyRequestSender.java:219)
	at com.ning.http.client.providers.netty.request.NettyRequestSender.sendRequestWithCertainForceConnect(NettyRequestSender.java:140)
	at com.ning.http.client.providers.netty.request.NettyRequestSender.sendRequest(NettyRequestSender.java:117)
	at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.execute(NettyAsyncHttpProvider.java:87)
	at com.ning.http.client.AsyncHttpClient.executeRequest(AsyncHttpClient.java:506)
	at com.ning.http.client.AsyncHttpClient.executeRequest(AsyncHttpClient.java:528)
	at qunar.tc.qconfig.client.staticswitch.SwitchHttpClient.getStatus(SwitchHttpClient.java:31)
	at qunar.tc.qconfig.client.staticswitch.StaticSwitcher.queryStatus(StaticSwitcher.java:96)
	at qunar.tc.qconfig.client.staticswitch.StaticSwitcher.run(StaticSwitcher.java:141)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by slandelle** [comment]
AHC 1 has been dead for a very long time. Please upgrade to version 2.
