### ISSUE TITLE
NoSuchMethodError: 'io.netty.bootstrap.AbstractBootstrap io.netty.bootstrap.Bootstrap.channelFactory(io.netty.channel.ChannelFactory)'

### ISSUE THREAD

**Issue by RussiaVk** [AsyncHttpClient/async-http-client#1789]
```
Exception in thread "main" java.lang.NoSuchMethodError: 'io.netty.bootstrap.AbstractBootstrap io.netty.bootstrap.Bootstrap.channelFactory(io.netty.channel.ChannelFactory)'
	at org.asynchttpclient.netty.channel.ChannelManager.newBootstrap(ChannelManager.java:162)
	at org.asynchttpclient.netty.channel.ChannelManager.<init>(ChannelManager.java:149)
	at org.asynchttpclient.DefaultAsyncHttpClient.<init>(DefaultAsyncHttpClient.java:92)
	at org.asynchttpclient.DefaultAsyncHttpClient.<init>(DefaultAsyncHttpClient.java:74)
	at org.asynchttpclient.Dsl.asyncHttpClient(Dsl.java:28)
```

**Comment by RussiaVk** [comment]
maven conflict
