### ISSUE TITLE
NPE in at org.asynchttpclient.netty.channel.Channels.setAttribute(Channels.java:36)

### ISSUE THREAD

**Issue by xiaoawo** [AsyncHttpClient/async-http-client#2042]
java.lang.NullPointerException
	at org.asynchttpclient.netty.channel.Channels.setAttribute(Channels.java:36)
	at org.asynchttpclient.netty.channel.Channels.setDiscard(Channels.java:40)
	at org.asynchttpclient.netty.NettyResponseFuture.cancel(NettyResponseFuture.java:183)

**Comment by xiaoawo** [comment]
I noticed that in the `done()` and `abort()` methods, the `channel` is set to `null`. If the code at line 182 (`channel != null`) is executed at this time, and another thread executes `done()` or `abort()`, it may lead to a `NullPointerException` at `org.asynchttpclient.netty.channel.Channels.setAttribute(Channels.java:36)`.

**Comment by hyperxpro** [comment]
This is likely a race condition. Do you plan for a PR?

**Comment by xiaoawo** [comment]
> This is likely a race condition. Do you plan for a PR?

yes，I will handle it in the next two days and provide a PR.

**Comment by pratt4** [comment]
Hi, I’d like to work on this
if it's still not done

**Comment by pratt4** [comment]
Hi, I have opened a PR, please review
