### ISSUE TITLE
"Too many open files" when adding a lot of requests at once

### ISSUE THREAD

**Issue by Rogach** [AsyncHttpClient/async-http-client#220]
When I'm trying to to process a lot (>1000) requests in parallel, I get lots of `java.nio.SocketException: Too many open files`. The code I used is as follows (Scala syntax):

``` scala
val client = new AsyncHttpClient()
(1 to 1000).foreach { i =>
  client.executeRequest(
    (new RequestBuilder()).setUrl("http://en.wikipedia.org/wiki/Main_Page").build(),
    new AsyncCompletionHandler[Int] {
      def onCompleted(response: Response) = 0
      override def onThrowable(t: Throwable) = {
        t.printStackTrace
      }
    }
  )
}
```

Exception stack trace:

```
java.net.SocketException: Too many open files
    at sun.nio.ch.Net.socket0(Native Method)
    at sun.nio.ch.Net.socket(Net.java:97)
    at sun.nio.ch.SocketChannelImpl.<init>(SocketChannelImpl.java:84)
    at sun.nio.ch.SelectorProviderImpl.openSocketChannel(SelectorProviderImpl.java:37)
    at java.nio.channels.SocketChannel.open(SocketChannel.java:105)
    at org.jboss.netty.channel.socket.nio.NioClientSocketChannel.newSocket(NioClientSocketChannel.java:39)
    at org.jboss.netty.channel.socket.nio.NioClientSocketChannel.<init>(NioClientSocketChannel.java:78)
    at org.jboss.netty.channel.socket.nio.NioClientSocketChannelFactory.newChannel(NioClientSocketChannelFactory.java:175)
    at org.jboss.netty.channel.socket.nio.NioClientSocketChannelFactory.newChannel(NioClientSocketChannelFactory.java:82)
    at org.jboss.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:213)
    at org.jboss.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:183)
    at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.doConnect(NettyAsyncHttpProvider.java:1059)
    at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.execute(NettyAsyncHttpProvider.java:916)
    at com.ning.http.client.AsyncHttpClient.executeRequest(AsyncHttpClient.java:512)
        ...
```

Maybe I'm doing something wrong?

**Comment by mbaglay** [comment]
Have the same problem even if I run only few requests. For every request about 200 new **pipe** and **anon_inode** are open. Also, they are open even if request is finished no matter with success or fail.
