### ISSUE TITLE
ApacheAsyncHttpProvider NPE

### ISSUE THREAD

**Issue by srirama-rayaprolu** [AsyncHttpClient/async-http-client#485]
Under Heavy load the apache provider throwing NPE. It is also observed, it is opening more number of threads like 10000 threads.

Version: async-http-client-1.8.3

java.lang.NullPointerException
        at com.ning.http.client.providers.apache.ApacheAsyncHttpProvider.execute(ApacheAsyncHttpProvider.java:211)
        at com.ning.http.client.AsyncHttpClient.executeRequest(AsyncHttpClient.java:524)
        at com.ning.http.client.AsyncHttpClient$BoundRequestBuilder.execute(AsyncHttpClient.java:236)

**Comment by slandelle** [comment]
Closing as provider was dropped in 1.9
