### ISSUE TITLE
TimeoutsHolder isn't threadsafe

### ISSUE THREAD

**Issue by slandelle** [AsyncHttpClient/async-http-client#534]
Causing NPE:

```
java.lang.NullPointerException
    at com.ning.http.client.providers.netty.timeout.TimeoutsHolder.cancel(TimeoutsHolder.java:27)
    at com.ning.http.client.providers.netty.timeout.IdleConnectionTimeoutTimerTask.run(IdleConnectionTimeoutTimerTask.java:66)
```

**Comment by SohumB** [comment]
> t
