### ISSUE TITLE
Gradle error 'Multiple dex file..' when incremental build option is enabled

### ISSUE THREAD

**Issue by tmsbn** [AsyncHttpClient/async-http-client#562]
When the incremental build option is enabled in Android Studio(0.5.9), gradle keep throwing this error after building the project

 Output:
    UNEXPECTED TOP-LEVEL EXCEPTION:
    com.android.dex.DexException: Multiple dex files define Lcom/loopj/android/http/AsyncHttpClient$1;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:594)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:552)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:533)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:170)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:439)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:287)
        at com.android.dx.command.dexer.Main.run(Main.java:230)
        at com.android.dx.command.dexer.Main.main(Main.java:199)
        at com.android.dx.command.Main.main(Main.java:103)

Any idea how to resolve this issue?

**Comment by nikitoSha** [comment]
What does it means "Wrong project"? Can you write more info about it? How to fix?

**Comment by slandelle** [comment]
@nikitoSha Let's look at it the other way: what makes you think this is the project you're looking for?

**Comment by nikitoSha** [comment]
@slandelle , You go aside. I had a similar error after updating the studio to the latest version, but in my case the problem is related to another library:

>Error:Execution failed for task ':app:transformDexArchiveWithDexMergerForDebug'.
com.android.build.api.transform.TransformException: com.android.dex.DexException: Multiple dex files define Lcom/koushikdutta/async/http/server/UnknownRequestBody;`

**Comment by nikitoSha** [comment]
I already install 
> compile 'com.android.support:multidex:1.0.2'
But error exist
