### ISSUE TITLE
Not able to perform a redirect when Location returns with a URL containing semicolon in the Path

### ISSUE THREAD

**Issue by feltraco** [AsyncHttpClient/async-http-client#668]
Dear all,

We got an unexpected behaviour when the response for a GET returns a 302, and in the Location header has a URL containing a semicolon in the Path component.

It is always reproducible and it is not just a matter of changing the Path for the URL (remove the semicolon) because we connect to a large number of different sources and we don't have any control over them.

For example ("curl" notation):
> GET /singlePath/file/pdfFile
< HTTP/1.1 302 Found
< Location: https://mycontainer.s3.amazonaws.com:443/demo/2014-08-14/2014-08-14T18:54:49;newspaper:171;issue:16124.pdf

The top level application runs in Play Framework 2.1.3 for Scala 2.10.3 - and the class that uses **async-http-client** is **_play.api.libs.ws.WS.WSRequestHolder**_. 

We have tried some combinations of async-http-client + netty and got almost the same error - varying in the error message.

**Some examples:**
1. With default dependencies for Play Framework:

```
"io.netty" % "netty" % "3.6.3.Final",
"com.ning" % "async-http-client" % "1.7.6",
```

1.a. Stacktrace:

```
Caused by: java.nio.channels.UnresolvedAddressException
    at sun.nio.ch.Net.checkAddress(Net.java:127)
    at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:644)
    at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink.connect(NioClientSocketPipelineSink.java:108)
    at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink.eventSunk(NioClientSocketPipelineSink.java:70)
    at org.jboss.netty.handler.ssl.SslHandler.handleDownstream(SslHandler.java:596)
    at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.handleDownstream(OneToOneEncoder.java:54)
    at org.jboss.netty.handler.codec.http.HttpClientCodec.handleDownstream(HttpClientCodec.java:97)
    at org.jboss.netty.handler.stream.ChunkedWriteHandler.handleDownstream(ChunkedWriteHandler.java:109)
    at org.jboss.netty.channel.Channels.connect(Channels.java:634)
    at org.jboss.netty.channel.AbstractChannel.connect(AbstractChannel.java:207)
    at org.jboss.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:229)
    at org.jboss.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:182)
    at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.doConnect(NettyAsyncHttpProvider.java:999)
    at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.execute(NettyAsyncHttpProvider.java:866)
    at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.nextRequest(NettyAsyncHttpProvider.java:1311)
    at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.nextRequest(NettyAsyncHttpProvider.java:1307)
    at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.redirect(NettyAsyncHttpProvider.java:2039)
    at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.access$2000(NettyAsyncHttpProvider.java:137)
    at com.ning.http.client.providers.netty.NettyAsyncHttpProvider$HttpProtocol.handle(NettyAsyncHttpProvider.java:2225)
    at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.messageReceived(NettyAsyncHttpProvider.java:1128)
    at org.jboss.netty.handler.stream.ChunkedWriteHandler.handleUpstream(ChunkedWriteHandler.java:142)
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
    at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459)
    at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
    at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
    at org.jboss.netty.handler.codec.http.HttpClientCodec.handleUpstream(HttpClientCodec.java:92)
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
    at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
    at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:109)
    at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
    at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:90)
    at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
```
1. Another combination:
   
   "io.netty" % "netty" % "3.9.2.Final",
   "com.ning" % "async-http-client" % "1.8.13",

2.a. Stacktrace:

```
Unexpected I/O exception on channel [id: 0x605f9c92, /10.0.0.56:34029 :> demo.myserver.com/17.15.25.14:443]
java.lang.NullPointerException: uri.host
    at com.ning.http.client.RequestBuilderBase.setURI(RequestBuilderBase.java:385) ~[com.ning.async-http-client-1.8.13.jar:na]
    at com.ning.http.client.RequestBuilderBase.setUrl(RequestBuilderBase.java:380) ~[com.ning.async-http-client-1.8.13.jar:na]
    at com.ning.http.client.RequestBuilder.setUrl(RequestBuilder.java:155) ~[com.ning.async-http-client-1.8.13.jar:na]
    at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.redirect(NettyAsyncHttpProvider.java:2014) ~[com.ning.async-http-client-1.8.13.jar:na]
    at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.access$2500(NettyAsyncHttpProvider.java:161) ~[com.ning.async-http-client-1.8.13.jar:na]
    at com.ning.http.client.providers.netty.NettyAsyncHttpProvider$HttpProtocol.handle(NettyAsyncHttpProvider.java:2208) ~[com.ning.async-http-client-1.8.13.jar:na]
    at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.messageReceived(NettyAsyncHttpProvider.java:1227) ~[com.ning.async-http-client-1.8.13.jar:na]
    at org.jboss.netty.handler.stream.ChunkedWriteHandler.handleUpstream(ChunkedWriteHandler.java:142) ~[io.netty.netty-3.9.2.Final.jar:na]
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296) ~[io.netty.netty-3.9.2.Final.jar:na]
    at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459) ~[io.netty.netty-3.9.2.Final.jar:na]
    at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536) ~[io.netty.netty-3.9.2.Final.jar:na]
    at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435) ~[io.netty.netty-3.9.2.Final.jar:na]
    at org.jboss.netty.handler.codec.http.HttpClientCodec.handleUpstream(HttpClientCodec.java:92) ~[io.netty.netty-3.9.2.Final.jar:na]
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296) ~[io.netty.netty-3.9.2.Final.jar:na]
    at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462) ~[io.netty.netty-3.9.2.Final.jar:na]
    at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443) ~[io.netty.netty-3.9.2.Final.jar:na]
    at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303) ~[io.netty.netty-3.9.2.Final.jar:na]
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) ~[io.netty.netty-3.9.2.Final.jar:na]
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) ~[io.netty.netty-3.9.2.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) ~[io.netty.netty-3.9.2.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) ~[io.netty.netty-3.9.2.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318) ~[io.netty.netty-3.9.2.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) ~[io.netty.netty-3.9.2.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) ~[io.netty.netty-3.9.2.Final.jar:na]
```
1. Another combination
   
   "io.netty" % "netty" % "3.9.2.Final",
   "com.ning" % "async-http-client" % "1.7.24",

3.a. Stacktrace

```
java.nio.channels.UnresolvedAddressException: null
    at sun.nio.ch.Net.checkAddress(Net.java:127) ~[na:1.7.0_55]
    at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:644) ~[na:1.7.0_55]
    at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink.connect(NioClientSocketPipelineSink.java:108) ~[io.netty.netty-3.9.2.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink.eventSunk(NioClientSocketPipelineSink.java:70) ~[io.netty.netty-3.9.2.Final.jar:na]
    at org.jboss.netty.handler.ssl.SslHandler.handleDownstream(SslHandler.java:586) ~[io.netty.netty-3.9.2.Final.jar:na]
    at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.handleDownstream(OneToOneEncoder.java:54) ~[io.netty.netty-3.9.2.Final.jar:na]
    at org.jboss.netty.handler.codec.http.HttpClientCodec.handleDownstream(HttpClientCodec.java:97) ~[io.netty.netty-3.9.2.Final.jar:na]
    at org.jboss.netty.handler.stream.ChunkedWriteHandler.handleDownstream(ChunkedWriteHandler.java:109) ~[io.netty.netty-3.9.2.Final.jar:na]
    at org.jboss.netty.channel.Channels.connect(Channels.java:634) ~[io.netty.netty-3.9.2.Final.jar:na]
    at org.jboss.netty.channel.AbstractChannel.connect(AbstractChannel.java:207) ~[io.netty.netty-3.9.2.Final.jar:na]
    at org.jboss.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:229) ~[io.netty.netty-3.9.2.Final.jar:na]
    at org.jboss.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:182) ~[io.netty.netty-3.9.2.Final.jar:na]
    at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.doConnect(NettyAsyncHttpProvider.java:1038) ~[com.ning.async-http-client-1.7.24.jar:na]
    at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.execute(NettyAsyncHttpProvider.java:905) ~[com.ning.async-http-client-1.7.24.jar:na]
    at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.nextRequest(NettyAsyncHttpProvider.java:1329) ~[com.ning.async-http-client-1.7.24.jar:na]
    at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.nextRequest(NettyAsyncHttpProvider.java:1325) ~[com.ning.async-http-client-1.7.24.jar:na]
    at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.redirect(NettyAsyncHttpProvider.java:2024) ~[com.ning.async-http-client-1.7.24.jar:na]
    at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.access$2400(NettyAsyncHttpProvider.java:158) ~[com.ning.async-http-client-1.7.24.jar:na]
    at com.ning.http.client.providers.netty.NettyAsyncHttpProvider$HttpProtocol.handle(NettyAsyncHttpProvider.java:2198) ~[com.ning.async-http-client-1.7.24.jar:na]
    at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.messageReceived(NettyAsyncHttpProvider.java:1163) ~[com.ning.async-http-client-1.7.24.jar:na]
    at org.jboss.netty.handler.stream.ChunkedWriteHandler.handleUpstream(ChunkedWriteHandler.java:142) ~[io.netty.netty-3.9.2.Final.jar:na]
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296) ~[io.netty.netty-3.9.2.Final.jar:na]
    at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459) ~[io.netty.netty-3.9.2.Final.jar:na]
    at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536) ~[io.netty.netty-3.9.2.Final.jar:na]
    at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435) ~[io.netty.netty-3.9.2.Final.jar:na]
    at org.jboss.netty.handler.codec.http.HttpClientCodec.handleUpstream(HttpClientCodec.java:92) ~[io.netty.netty-3.9.2.Final.jar:na]
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296) ~[io.netty.netty-3.9.2.Final.jar:na]
    at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462) ~[io.netty.netty-3.9.2.Final.jar:na]
    at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443) ~[io.netty.netty-3.9.2.Final.jar:na]
    at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303) ~[io.netty.netty-3.9.2.Final.jar:na]
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) ~[io.netty.netty-3.9.2.Final.jar:na]
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) ~[io.netty.netty-3.9.2.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) ~[io.netty.netty-3.9.2.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) ~[io.netty.netty-3.9.2.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318) ~[io.netty.netty-3.9.2.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) ~[io.netty.netty-3.9.2.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) ~[io.netty.netty-3.9.2.Final.jar:na]
```

**Comment by lalkhum** [comment]
Whats the "io.netty:netty" version for AHC 1.9.11?
