### ISSUE TITLE
AHC-1.9 Netty3 provider throws NullPointerException on retry if maxConnectionsPerHost is enabled

### ISSUE THREAD

**Issue by jonas-ren** [AsyncHttpClient/async-http-client#900]
In AHC-1.9, if maxConnectionsPerHost is enabled and the client is sending a second request on either retry or redirect, it will cause an NPE. Stack trace:

Jun 01, 2015 11:55:34 AM org.jboss.netty.channel.DefaultChannelFuture
WARNING: An exception was thrown by ChannelFutureListener.
java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
	at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
	at com.ning.http.client.providers.netty.channel.ChannelManager.registerOpenChannel(ChannelManager.java:387)
	at com.ning.http.client.providers.netty.request.NettyConnectListener.writeRequest(NettyConnectListener.java:80)
	at com.ning.http.client.providers.netty.request.NettyConnectListener.onFutureSuccess(NettyConnectListener.java:107)
	at com.ning.http.client.providers.netty.request.NettyConnectListener.operationComplete(NettyConnectListener.java:138)
        at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:431)
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListeners(DefaultChannelFuture.java:422)
	at org.jboss.netty.channel.DefaultChannelFuture.setSuccess(DefaultChannelFuture.java:362)
	at org.jboss.netty.channel.socket.nio.NioWorker$RegisterTask.run(NioWorker.java:156)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.processTaskQueue(AbstractNioSelector.java:372)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:296)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

I investigated a bit and seems like the root cause is that NettyRequestSender doesn't set partitionKey if reclaimCache is true (always true on retry). See: https://github.com/AsyncHttpClient/async-http-client/blob/master/providers/netty3/src/main/java/org/asynchttpclient/netty/request/NettyRequestSender.java#L266-285

This is causing paritionKey to passed as null to ChannelManager, which throws NPE on put to ConcurrentMap. See: https://github.com/AsyncHttpClient/async-http-client/blob/master/providers/netty3/src/main/java/org/asynchttpclient/netty/channel/ChannelManager.java#L298

Since the ConcurrentMap expect both key and value not to be null, I think it's not unlikely for it to throw NPE on some other cases. Feels like we should be more strict about key/value null checking here.

**Comment by slandelle** [comment]
Fixed, thanks!
