### ISSUE TITLE
Netty: Protocol.onClose wrongly invoked on unexpected exception instead of onError

### ISSUE THREAD

**Issue by jfarcand** [AsyncHttpClient/async-http-client#904]
```java
org.jboss.netty.handler.codec.frame.CorruptedFrameException: Max frame length of 10240 has been exceeded.
	at org.jboss.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder.protocolViolation(WebSocket08FrameDecoder.java:381) ~[tubes-debug.jar:na]
	at org.jboss.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder.decode(WebSocket08FrameDecoder.java:242) ~[tubes-debug.jar:na]
	at org.jboss.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder.decode(WebSocket08FrameDecoder.java:71) ~[tubes-debug.jar:na]
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:500) ~[tubes-debug.jar:na]
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435) ~[tubes-debug.jar:na]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) ~[tubes-debug.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [tubes-debug.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) [tubes-debug.jar:na]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) [tubes-debug.jar:na]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) [tubes-debug.jar:na]
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) [tubes-debug.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) [tubes-debug.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337) [tubes-debug.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) [tubes-debug.jar:na]
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) [tubes-debug.jar:na]
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [tubes-debug.jar:na]
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [tubes-debug.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
```

**Comment by slandelle** [comment]
Could you elaborate on the exact issue please?

**Comment by slandelle** [comment]
Fix tentative reverted until we're sure about the proper fix.

**Comment by slandelle** [comment]
The thing here is that [Netty closes the connection before notifying the exception](https://github.com/netty/netty/blob/netty-3.10.4.Final/src/main/java/org/jboss/netty/handler/codec/http/websocketx/WebSocket08FrameDecoder.java#L384-L390).

As a consequence, the channel gets closed and we have no idea why and can't react to it. I'm not sure that the sequence is the same with Netty 4.

**Comment by slandelle** [comment]
Sadly, nothing we can do.
