### ISSUE TITLE
SNI + VirtualHost != success

### ISSUE THREAD

**Issue by jxtps** [AsyncHttpClient/async-http-client#927]
I need to make local https requests to servers that run multiple websites. This means that the url is something like `https://localhost/...`, with the virtual host set to `example.com`. Can't go to example.com as the purpose is to test the current server which is behind the load balancer that actually serves example.com, and can't use http since the nginx configuration redirects to https since otherwise our actual site visitors wouldn't get https. 

The certificate returned is indeed for `example.com` (in case we ever remove the load balancer, and well, it's a great certificate), but the hostname verification fails with a `java.security.cert.CertificateException: No subject alternative DNS name matching localhost found.`. 

It would be great if the hostname verification took the virtual host specified into account.

**Comment by slandelle** [comment]
Supporting this is actually not straightforward: virtual host should not only be taken into account for hostname validation, but for connection pooling too.

**Comment by slandelle** [comment]
And having access to such a set up would help.

**Comment by jxtps** [comment]
Setup: nslookup www.google.com, then do a request to one of the IP addresses with the virtual host "www.google.com"?

Calling AsyncHttpClient from Play, it would look something like: 

```scala
import scala.concurrent.ExecutionContext.Implicits.global
WS.url("https://74.125.239.48").
  withVirtualHost("www.google.com").
  get().map(response => Logger.info("Hello Google! " + response.status + ", " + response.body.take(1024))).
  recover {
  case ex: Exception => Logger.info("Failed!", ex)
}
```
Which at present logs: 

```
INFO application - Failed!
java.net.ConnectException: General SSLEngine problem
        at com.ning.http.client.providers.netty.request.NettyConnectListener.onFutureFailure(NettyConnectListener.java:128) ~[async-http-client-1.9.21.jar:na]
        at com.ning.http.client.providers.netty.request.NettyConnectListener.access$200(NettyConnectListener.java:37) ~[async-http-client-1.9.21.jar:na]
        at com.ning.http.client.providers.netty.request.NettyConnectListener$1.operationComplete(NettyConnectListener.java:101) ~[async-http-client-1.9.21.jar:na]
        at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:409) ~[netty-3.10.3.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelFuture.notifyListeners(DefaultChannelFuture.java:395) ~[netty-3.10.3.Final.jar:na]
Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
        at sun.security.ssl.Handshaker.checkThrown(Handshaker.java:1431) ~[na:1.8.0_45]
        at sun.security.ssl.SSLEngineImpl.checkTaskThrown(SSLEngineImpl.java:535) ~[na:1.8.0_45]
        at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:813) ~[na:1.8.0_45]
        at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781) ~[na:1.8.0_45]
        at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624) ~[na:1.8.0_45]
Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:192) ~[na:1.8.0_45]
        at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1728) ~[na:1.8.0_45]
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:304) ~[na:1.8.0_45]
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296) ~[na:1.8.0_45]
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1478) ~[na:1.8.0_45]
Caused by: java.security.cert.CertificateException: No subject alternative names matching IP address 74.125.239.48 found
        at sun.security.util.HostnameChecker.matchIP(HostnameChecker.java:167) ~[na:1.8.0_45]
        at sun.security.util.HostnameChecker.match(HostnameChecker.java:93) ~[na:1.8.0_45]
        at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:455) ~[na:1.8.0_45]
        at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:436) ~[na:1.8.0_45]
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:252) ~[na:1.8.0_45]
```

**Comment by schmitch** [comment]
Play! 2.5.0-M1 has the alpha but this still won't work @slandelle

**Comment by slandelle** [comment]
@schmitch Not an AHC issue:

```java
try (AsyncHttpClient client = asyncHttpClient()) {

    Response response = client.executeRequest(new RequestBuilder("GET")//
        .setUrl("https://74.125.239.48")//
        .setVirtualHost("www.google.com").build()).get();

    System.err.println(response);
}
```

All good.

**Comment by joymufeng** [comment]
@slandelle I also meet this problem in AHC 1.9.39, is there any workaround in AHC 1.9.39?
The following codes works fine:
```
AsyncHttpClient client = new AsyncHttpClient();
Response resp = client.executeRequest(new RequestBuilder("GET")
     .setUrl("https://github.com")
     .build()).get();
System.out.println(resp.getStatusCode());
```
But these codes don't work:
```
AsyncHttpClient client = new AsyncHttpClient();
Response resp = client.executeRequest(new RequestBuilder("GET")
       .setUrl("https://192.30.253.112")
       .setVirtualHost("github.com").build()).get();
System.out.println(resp.getStatusCode());
```
```
Exception in thread "main" java.util.concurrent.ExecutionException: java.net.ConnectException: General SSLEngine problem
	at com.ning.http.client.providers.netty.future.NettyResponseFuture.abort(NettyResponseFuture.java:231)
	at com.ning.http.client.providers.netty.request.NettyConnectListener.onFutureFailure(NettyConnectListener.java:137)
	at com.ning.http.client.providers.netty.request.NettyConnectListener.access$200(NettyConnectListener.java:37)
	at com.ning.http.client.providers.netty.request.NettyConnectListener$1.operationComplete(NettyConnectListener.java:104)
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:409)
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListeners(DefaultChannelFuture.java:395)
	at org.jboss.netty.channel.DefaultChannelFuture.setFailure(DefaultChannelFuture.java:362)
	at org.jboss.netty.handler.ssl.SslHandler.setHandshakeFailure(SslHandler.java:1460)
	at org.jboss.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1314)
	at org.jboss.netty.handler.ssl.SslHandler.decode(SslHandler.java:852)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:425)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:310)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: General SSLEngine problem
	at com.ning.http.client.providers.netty.request.NettyConnectListener.onFutureFailure(NettyConnectListener.java:133)
	... 25 more
Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
	at sun.security.ssl.Handshaker.checkThrown(Handshaker.java:1431)
	at sun.security.ssl.SSLEngineImpl.checkTaskThrown(SSLEngineImpl.java:535)
	at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:813)
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781)
	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
	at org.jboss.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1218)
	... 18 more
Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1728)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:304)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1497)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:212)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
	at sun.security.ssl.Handshaker$1.run(Handshaker.java:919)
	at sun.security.ssl.Handshaker$1.run(Handshaker.java:916)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1369)
	at org.jboss.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1392)
	at org.jboss.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1255)
	... 18 more
Caused by: java.security.cert.CertificateException: No subject alternative names matching IP address 192.30.253.112 found
	at sun.security.util.HostnameChecker.matchIP(HostnameChecker.java:167)
	at sun.security.util.HostnameChecker.match(HostnameChecker.java:93)
	at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:455)
	at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:436)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:252)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:136)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1484)
	... 26 more
```

**Comment by slandelle** [comment]
@joymufeng Your latest message is unrelated to the original issue.
Then, your sample works fine with AHC2, and AHC1 has reached EOL and is no longer maintained. Please upgrade.

**Comment by joymufeng** [comment]
@slandelle My project relies on Netty 4.1.5.Final. Is it possible to work with both Netty 4.1.5.Final and AHC 2.0.15. If not, I have to wait for AHC 2.1.0.
