### ISSUE TITLE
Custom HostnameVerifier never called, connection prematurely rejected

### ISSUE THREAD

**Issue by jxtps** [AsyncHttpClient/async-http-client#928]
See https://github.com/AsyncHttpClient/async-http-client/issues/927 and https://github.com/playframework/playframework/issues/4796 

I need to customize the hostname checks for some requests to localhost, so I've tried injecting a custom HostnameVerifier, but the Sun HostnameChecker causes an exception without ever calling my code. 

This may be caused by the fix to https://github.com/AsyncHttpClient/async-http-client/issues/927 where the sslEngine is told to use "HTTPS" as the endpoint verification algorithm, [see this line](https://github.com/AsyncHttpClient/async-http-client/blob/cdcd4d7e747c924c1d0ba6afa000776f8dd37921/src/main/java/com/ning/http/client/SSLEngineFactory.java#L55).

**Comment by slandelle** [comment]
AFAIK, there's no way to plug a custom HostnameVerifier on the SSLEngine API.
It's only supported by HttpsUrlConnection, which is the old blocking API.

**Comment by jxtps** [comment]
Ah. The version of async-http-client that ships with Play still has the AsyncHttpClientConfig.Builder.setHostnameVerifier() method, I can see that it's gone in master.

**Comment by wsargent** [comment]
@slandelle the hostname verifier is called by NettyConnectListener after the handshake has completed https://github.com/wsargent/async-http-client/commit/8e4d787565b9bc3929c9e24c82accd6c8b7233e7#diff-afb8fbb32a9b370f66b6fbdd6104f354R64

**Comment by jxtps** [comment]
Could the "HTTPS" endpoint verification happen as part of the handshake, i.e. prior to calling the hostname verifier?

Note that one of the "Caused by" exceptions appear to be in the middle of handshaking: 

```
java.net.ConnectException: General SSLEngine problem
        at com.ning.http.client.providers.netty.request.NettyConnectListener.onFutureFailure(NettyConnectListener.java:128) ~[async-http-client-1.9.21.jar:na]
        at com.ning.http.client.providers.netty.request.NettyConnectListener.access$200(NettyConnectListener.java:37) ~[async-http-client-1.9.21.jar:na]
        at com.ning.http.client.providers.netty.request.NettyConnectListener$1.operationComplete(NettyConnectListener.java:101) ~[async-http-client-1.9.21.jar:na]
        at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:409) ~[netty-3.10.3.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelFuture.notifyListeners(DefaultChannelFuture.java:395) ~[netty-3.10.3.Final.jar:na]
Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
        at sun.security.ssl.Handshaker.checkThrown(Handshaker.java:1431) ~[na:1.8.0_45]
        at sun.security.ssl.SSLEngineImpl.checkTaskThrown(SSLEngineImpl.java:535) ~[na:1.8.0_45]
        at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:813) ~[na:1.8.0_45]
        at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781) ~[na:1.8.0_45]
        at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624) ~[na:1.8.0_45]
Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:192) ~[na:1.8.0_45]
        at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1728) ~[na:1.8.0_45]
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:304) ~[na:1.8.0_45]
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296) ~[na:1.8.0_45]
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1478) ~[na:1.8.0_45]
Caused by: java.security.cert.CertificateException: No subject alternative names matching IP address 74.125.239.48 found
        at sun.security.util.HostnameChecker.matchIP(HostnameChecker.java:167) ~[na:1.8.0_45]
        at sun.security.util.HostnameChecker.match(HostnameChecker.java:93) ~[na:1.8.0_45]
        at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:455) ~[na:1.8.0_45]
        at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:436) ~[na:1.8.0_45]
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:252) ~[na:1.8.0_45]
```

**Comment by slandelle** [comment]
@wsargent The Netty provider no longer support setting a HostnameVerifier.

**Comment by slandelle** [comment]
@wsargent @jxtps The original usage of a `HostnameVerifier` in AHC was a clearly an abuse.
It actually served as a HostnameChecker, caused tons of security issues and didn't honor `HostnameVerifier`'s expected behavior.

> From javax.net.ssl.HostnameVerifier javadoc:
During handshaking, if the URL's hostname and the server's identification hostname mismatch, the verification mechanism can call back to implementers of this interface to determine if this connection should be allowed.

Clearly, it's a fallback in case of some specific certificate validation use cases.
JDK7 introduced a way to ask a SSLEngine to trigger the HTTPS validations, but we still lack there the ability to set a HostnameVerifier. AFAIK, this is only currently possible on HttpsUrlConnection.



hack and IMHO, it shouldn't have been something different 

inherited from  and was leading to security issues. 

During handshaking, if the URL's hostname and the server's identification hostname mismatch, the verification mechanism can call back to implementers of this interface to determine if this connection should be allowed.



Even in @wsargent 's PR, it didn't serve the expected purpose as it was called on :

**Comment by wsargent** [comment]
+1 what @slandelle said
