### ISSUE TITLE
Cannot create parent directories for requested File location - Fatal Exception: java.lang.AssertionError

### ISSUE THREAD

**Issue by marquinhojfr** [AsyncHttpClient/async-http-client#962]
This error only occurs for some users

com.loopj.android.http.Utils.asserts (Utils.java:39)
com.loopj.android.http.FileAsyncHttpResponseHandler.<init> (FileAsyncHttpResponseHandler.java:69)
com.loopj.android.http.FileAsyncHttpResponseHandler.<init> (FileAsyncHttpResponseHandler.java:55)
com.loopj.android.http.FileAsyncHttpResponseHandler.<init> (FileAsyncHttpResponseHandler.java:45)
package.name.Midia$2.<init> (Midia.java:166)
package.name.Midia.downloadVideo (Midia.java:166)
package.name.ListMidiasAdapter$8.onClick (ListMidiasAdapter.java:190)
android.view.View.performClick (View.java:3511)
android.view.View$PerformClick.run (View.java:14109)
android.os.Handler.handleCallback (Handler.java:605)
android.os.Looper.loop (Looper.java:137)
android.app.ActivityThread.main (ActivityThread.java:4424)
java.lang.reflect.Method.invokeNative (Method.java)
dalvik.system.NativeStart.main (NativeStart.java)

**Comment by slandelle** [comment]
https://github.com/loopj/android-async-http/issues/876

**Comment by marquinhojfr** [comment]
But i'm using code from this github page

repositories {
    maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
}

compile 'com.loopj.android:android-async-http:1.4.8'

**Comment by marquinhojfr** [comment]
Sorry, I get the error now, even wrong page

**Comment by naveedahmad99** [comment]
05-10 00:38:14.552 4255-4255/com.islam.almunjidcomplete E/UncaughtException: java.lang.AssertionError: Cannot create parent directories for requested File location
                                                                                 at com.loopj.android.http.Utils.asserts(Utils.java:39)
                                                                                 at com.loopj.android.http.FileAsyncHttpResponseHandler.<init>(FileAsyncHttpResponseHandler.java:82)
                                                                                 at com.loopj.android.http.FileAsyncHttpResponseHandler.<init>(FileAsyncHttpResponseHandler.java:66)
                                                                                 at com.loopj.android.http.FileAsyncHttpResponseHandler.<init>(FileAsyncHttpResponseHandler.java:55)
                                                                                 at com.loopj.android.http.FileAsyncHttpResponseHandler.<init>(FileAsyncHttpResponseHandler.java:45)
                                                                                 at com.islam.almunjidcomplete.services.SkyElectricRestClient$1.<init>(SkyElectricRestClient.java:0)
                                                                                 at com.islam.almunjidcomplete.services.SkyElectricRestClient.getFileRequest(SkyElectricRestClient.java:64)
                                                                                 at com.islam.almunjidcomplete.services.DownloadService.downloadFile(DownloadService.java:91)
                                                                                 at com.islam.almunjidcomplete.services.DownloadService$2.handleMessage(DownloadService.java:120)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                 at android.os.Looper.loop(Looper.java:150)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5665)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:822)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:712)

**Comment by naveedahmad99** [comment]
compile 'com.loopj.android:android-async-http:1.4.9'

**Comment by slandelle** [comment]
Please take a few seconds to read this thread so you figure out what you're doing wrong.
